Reconnect improvements
lambdaclass/curse_of_myrra pull request #1003
Opened 2023-10-19 18:43 UTC by ncontinanza

Closes #786

2023-10-19 20:50 UTC, agustinesco requested changes
Tested the pr and the re-join option isn't being prompt when i manually exit the game as requested in the issue! but this makes me wonder, when do we want this option to appear? i exit'ed an on-goin game by killing the game pressing the "Play" button in the unity hud and when i go back to the lobbies the option isn't there

2023-10-24 16:07 UTC, AminArria requested changes
By the way, are you formatti

2023-10-24 16:07 UTC, AminArria commented on server/lib/dark_worlds_server_web/controllers/game_controller.ex
> +        player_exited_game =
Look at the `PlayerTracker` module, essentially what you should do is call something to trigger the removal of the player from

2023-10-24 16:07 UTC, AminArria commented on server/lib/dark_worlds_server/engine/runner.ex
> +    {:ok, game} = Game.exit_game(gen_server_state.server_game_state.game, player_id)
As I mentioned in the other PR, the engine should not have any notion about this kind of things

2023-10-24 16:07 UTC, AminArria commented on server/lib/dark_worlds_server_web/controllers/game_controller.ex
I see a lot of formatting changes in this file, please check that whoever you format follows our config https://github.com/lambdaclass/curse_of_myrra/blob/main/server/.formatter.exs

2023-10-27 14:23 UTC, ncontinanza commented on server/lib/dark_worlds_server_web/controllers/game_controller.ex
> +        player_exited_game =
Thanks, I hadn't thought of that. I used the remove_player function and afterwards check if the player exists to decide wether it should try to reconnect.

2023-10-27 15:26 UTC, ncontinanza commented on server/lib/dark_worlds_server_web/controllers/game_controller.ex
Fixed!

2023-10-30 16:40 UTC, AngieDutra reviewed
Some buttons like mute button and back button are not shoeing properly. Maybe you should revert the overrides and push those changes in Lobbies.unity

2023-10-30 18:02 UTC, ncontinanza commented
> Some buttons like mute button and back button are not shoeing properly. Maybe you should revert the overrides and push those changes in Lobbies.unity

Done! I tested it and everything seemed to be working fine in the Lobbies scene, but please double check

2023-11-09 19:56 UTC, closed without merging