[GH-987] Make bots flee from harmful zone
lambdaclass/curse_of_myrra pull request #1007
Opened 2023-10-19 20:34 UTC by agustinesco

Closes #987

2023-10-20 15:50 UTC, AminArria requested changes

2023-10-20 15:50 UTC, AminArria commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +  @decide_delay 500
nit: add suffix `_ms` to the variable name

2023-10-20 15:50 UTC, AminArria commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +      if bot_state && bot_state.alive do
Checking `bot_state.alive` here is redundant because we already check it in `decide_action/4` 

This also removed the need to check `bot_state`, this will never be `nil` unless we made a bug

2023-10-20 15:50 UTC, AminArria commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +  def decide_state(player_state, _bots_genserver_state) do
This should be called `decide_objective`, the word "state" is really overloaded and use too much so better to avoid it when we have clearer words

2023-10-20 18:24 UTC, agustinesco commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +        game_state = Runner.get_game(state.game_pid) |> Map.get(:myrra_state)
sounds good, i will just keep the game in the genserver state and update it here.

2023-10-20 19:16 UTC, agustinesco commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +  def decide_state(player_state, _bots_genserver_state) do
You're right! it's starting to get confusing to call everything "state". Changed

2023-10-20 19:16 UTC, agustinesco commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +  @decide_delay 500
Sounds good

2023-10-20 19:56 UTC, agustinesco commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +      if bot_state && bot_state.alive do
This check is here to stop the genservers calls of `Process.send_after(self(), {:decide_action, bot_id}, @decide_delay)` since even if it's being handled in the `decide_action/4` method it doesn't stop the calls since this is being called on each "decide_action" message. I'll avoid changing the bot_state to nil to keep consistency tho

2023-10-23 17:01 UTC, AminArria approved these changes
LGTM (but didn't live test it)

2023-10-23 17:23 UTC, AngieDutra submitted a review, later dismissed
Tested it and it works a lot better now!

2023-10-23 19:01 UTC, AngieDutra approved these changes
Tested it in mobile, tried a couple of variants and it worked great! Congrats ✨

2023-10-23 19:01 UTC, merged