Fix zone timer on reconnect
lambdaclass/curse_of_myrra pull request #1009
Opened 2023-10-20 15:37 UTC by tkz00

Registered the start time of the match, calculate based on that the time elapsed since the beginning of it, subtract from the time it takes to start shrinking the zone the time elapsed and display it.

2023-10-23 18:13 UTC, BertovDev requested changes
When timer reaches 0:

<img width="190" alt="Captura de pantalla 2023-10-23 a la(s) 14 44 43" src="https://github.com/lambdaclass/curse_of_myrra/assets/62818001/28ff022e-149d-4433-b883-822c77b7f7c9">

2023-10-24 13:55 UTC, BertovDev commented on client/Assets/Scripts/UI/MatchStatsController.cs
LGTM! consider doing something like this to improve code readability:

```
        ulong mapShrinkWaitMs = LobbyConnection
            .Instance
            .serverSettings
            .RunnerConfig
            .MapShrinkWaitMs;
```

2023-10-24 14:16 UTC, tkz00 commented on client/Assets/Scripts/UI/MatchStatsController.cs
Looks good! Already made the changes!

2023-10-24 19:53 UTC, ncontinanza requested changes
Working great! Just a little comment about the code

2023-10-24 19:53 UTC, ncontinanza commented on client/Assets/Scripts/UI/MatchStatsController.cs
> +                zoneTimer.text = "0";
In both cases, having `zoneTimer.text = remainingSeconds.ToString();` will do. What do you think of leaving that line only once outside de if/else? After that, maybe you can go further and rewrite the assignment as a single statement using ternary operation if you feel it more readable/cleaner.

2023-10-25 16:10 UTC, saugon commented on client/Assets/Scripts/SocketConnectionManager.cs
> +                        PlayerPrefs.SetString("matchStartTime", ((ulong)gameEvent.ServerTimestamp).ToString());
This approach to solving the issue could be appropriate only if it weren't possible to make any changes on the backend side.

In our case, the best approach is to obtain the current time directly from the backend and display it without requiring any calculations on the client side.

2023-10-25 21:10 UTC, tkz00 commented on client/Assets/Scripts/SocketConnectionManager.cs
> +                        PlayerPrefs.SetString("matchStartTime", ((ulong)gameEvent.ServerTimestamp).ToString());
That's right, it should be the backend's responsibility to calculate and return that information, I'll close this PR and we are going to fix the issue with the corresponding backend and client changes in a new PR.

2023-10-25 21:11 UTC, tkz00 commented
After some consideration we came to the conclusion the best approach to display the remaining time for the damage zone would be to return the number from the backend, instead of calculating it in the front end, so we'll close this PR and fix the problem properly in a future one.

2023-10-25 21:11 UTC, closed without merging