Make the bot target an entity in his proximity
lambdaclass/curse_of_myrra pull request #1017
Opened 2023-10-20 20:47 UTC by agustinesco

Now the bots will go straight to an entity in a range

2023-10-26 15:17 UTC, Nico-Sanchez requested changes
Nice refactor and additions you've done here @agustinesco. Congrats 🎉 !
The bots seem more alive now. The random movement is still weird but I think its job for another PR.

Left some comments to improve the code readability.

2023-10-26 15:17 UTC, Nico-Sanchez commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +  @visibility_max_range 2000
Let's explain what this variable does and what's the unit of it in the comment line, just like the one above.

2023-10-26 15:17 UTC, Nico-Sanchez commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +    # TODO replace this 400 with a function that determines if any skill would hit the enemy
The idea is to see if the enemy is reachable? If so the bot will attack otherwise will get closer?
If that's the case maybe we can add it to the "todo" tag or as a comment above the function.

2023-10-26 15:17 UTC, Nico-Sanchez commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +  defp do_action(bot_id, game_pid, _players, %{
Is this for loots? Maybe a comment would be nice so other devs doesn't have to guess.

2023-10-26 15:17 UTC, Nico-Sanchez commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +  end
😛 
(Beware the typo is everywhere)
```suggestion
  defp get_closest_entity(_, _) do
    %{}
  end
```

2023-10-26 15:21 UTC, agustinesco commented
> Also, why is the bot test deleted?

I deleted them since they were unit test and they wasn't being helpful, we should only do integration testing

2023-10-26 15:28 UTC, agustinesco commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +  end
whoops, should be fixed now

2023-10-26 15:31 UTC, agustinesco commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +  @visibility_max_range 2000
Sure thing!

2023-10-26 15:42 UTC, agustinesco commented on server/lib/dark_worlds_server/engine/bot_player.ex
> +  defp do_action(bot_id, game_pid, _players, %{
Yes! this match is for the loot entities, comment added

2023-10-26 20:54 UTC, Nico-Sanchez approved these changes

2023-10-27 14:25 UTC, AngieDutra approved these changes
LGTM ✨

2023-10-27 14:25 UTC, merged