Fix death splash
lambdaclass/curse_of_myrra pull request #1028
Opened 2023-10-23 21:15 UTC by BertovDev

2023-10-24 20:35 UTC, AngieDutra requested changes

2023-10-24 20:35 UTC, AngieDutra commented on client/Assets/Scripts/UI/DeathSplash/DeathSplashManager.cs
> +        // ShowEndGameScreen();
If this is not being used, I would delete it

2023-10-24 20:35 UTC, AngieDutra commented on client/Assets/Scripts/UI/DeathSplash/DeathSplashManager.cs
> +        print(SocketConnectionManager.Instance.GameHasEnded());
I believe you forgot a print here

2023-10-25 14:22 UTC, AngieDutra submitted a review, later dismissed
Tested in mobile and working great!

2023-10-25 17:19 UTC, agustinesco commented on client/Assets/Scripts/CustomLevelManager.cs
> +    public bool test = false;
I think we should delete this

2023-10-25 19:05 UTC, BertovDev commented on client/Assets/Scripts/CustomLevelManager.cs
> +    public bool test = false;
Done

2023-10-25 19:35 UTC, ncontinanza approved these changes
LGTM! Tested in Unity and Android

2023-10-25 19:43 UTC, agustinesco approved these changes
LGTM! the death splash seems to be working correctly, tested both unity and android versions

2023-10-25 19:44 UTC, merged