Integration tests
lambdaclass/curse_of_myrra pull request #1029
Opened 2023-10-23 21:55 UTC by martinacantaro

Test flow through the UI to create a lobby and start a game. 
To do: choose character and start game
To do: use Unity UI interaction library instead of calling scripts directly.

2023-11-01 18:07 UTC, ncontinanza commented
We noticed several auto-generated files such as client/Assets/InitTestScene638336713701830240.unity which shouldn't exist after running the whole suite of tests (https://forum.unity.com/threads/scene-testing.575920/)

2023-11-01 19:30 UTC, martinacantaro commented
> We noticed several auto-generated files such as client/Assets/InitTestScene638336713701830240.unity which shouldn't exist after running the whole suite of tests (https://forum.unity.com/threads/scene-testing.575920/)

Ready for review again!
- Those files are generated by running a test
- Sometimes they are deleted automatically, sometimes not. 
- In particular, they are not deleted automatically if you stop the test before it's completed
- We explored the solution of deleting these files in the test TearDown, but if you manually stop the test before completion, the TearDown would not run and that solution would not suffice
- Therefore, we added these files to the gitignore

2023-11-01 19:38 UTC, AngieDutra requested changes
<img width="226" alt="Captura de pantalla 2023-11-01 a la(s) 16 37 56" src="https://github.com/lambdaclass/curse_of_myrra/assets/82987608/924b52bf-b00e-4204-8916-ee0590ae497c">

I believe all test should pass so maybe recent merges broke some of them. This is something to check

2023-11-01 19:38 UTC, AngieDutra commented on .gitignore
> +client/Assets/*.unity
I haven't checked yet but I believe this will difficult developers when creating new scenes that we know are coming up. I would be specific. We know the file created always starts with InitTest, for example

2023-11-01 20:08 UTC, AngieDutra commented on .gitignore
> +client/Assets/*.unity
It turns out this is not an issue

2023-11-01 20:33 UTC, tkz00 commented on .gitignore
> +client/Assets/*.unity
I've made a little change just for clarity.

2023-11-01 20:47 UTC, tkz00 commented
Further investigation is needed to understand why certain tests fail, particularly those related to the server connection. When the "ServerIsHealthy" test fails, it will undoubtedly lead to the failure of many other tests. However, it's crucial for the "ServerIsHealthy" test to pass because its success is essential for obtaining accurate results from the rest of the tests. If "ServerIsHealthy" fails do not take into account the rest of the tests results and rerun them until "ServerIsHealthy" passes.

2023-11-03 15:14 UTC, AngieDutra requested changes

2023-11-03 15:14 UTC, AngieDutra commented on client/Assets/Scripts/UnityTests/PlayModeTests/ServerHealthCheck.cs
> +    IEnumerator CoClickButton(GameObject go)
I saw this in TestingUtils. Maybe use it here too?

2023-11-03 21:00 UTC, tkz00 commented on client/Assets/Scripts/UnityTests/PlayModeTests/ServerHealthCheck.cs
> +        GameObject newLobbyButton = GameObject.Find("NewLobbyButton");
You're right! I'll add the search for the element to click to the click method instead of repeating that line every time.

2023-11-07 14:11 UTC, AngieDutra requested changes

2023-11-07 14:19 UTC, tkz00 commented on client/Assets/Scripts/UnityTests/PlayModeTests/LobbiesUITest.cs
> +        //Assert.That(SceneManager.GetActiveScene().name, Is.EqualTo("Lobbies"));
Uncommented the line!

2023-11-07 16:36 UTC, AngieDutra submitted a review, later dismissed
LGTM ✨

2023-11-07 16:36 UTC, AngieDutra commented on client/Assets/Scripts/UnityTests/PlayModeTests/ServerHealthCheck.cs
I have a theory on how to make this tests better. The error when this test fails is the following:

<img width="715" alt="Captura de pantalla 2023-11-07 a la(s) 13 31 45" src="https://github.com/lambdaclass/curse_of_myrra/assets/82987608/3b93f6f6-0dbe-4310-a739-1ff530de8e06">
This indicates the socket check is failing when there is no instance of the player. We could control the check by running it when the player is available in the socket instance. This is an idea for a future implementation.

2023-11-07 16:36 UTC, AngieDutra commented on client/Assets/Scripts/UnityTests/PlayModeTests/ServerHealthCheck.cs
Maybe in issue #1020

2023-11-09 20:43 UTC, ncontinanza commented
I got this error when trying it out in my client:

```
MatchStart (13.971s)
---
Expected string length 6 but was 18. Strings differ at index 0.
  Expected: "Battle"
  But was:  "CharacterSelection"
  -----------^
---
at MatchStartFlow+<MatchStart>d__1.MoveNext () [0x00227] in /Users/ncontinanza/Projects/Lambdaclass/curse_of_myrra/client/Assets/Scripts/UnityTests/PlayModeTests/MatchStartFlow.cs:42
at UnityEngine.TestTools.TestEnumerator+<Execute>d__7.MoveNext () [0x0003a] in /Users/ncontinanza/Projects/Lambdaclass/curse_of_myrra/client/Library/PackageCache/com.unity.test-framework@1.1.33/UnityEngine.TestRunner/NUnitExtensions/Attributes/TestEnumerator.cs:46

```

Am I missing something?

2023-11-13 19:29 UTC, ncontinanza submitted a review, later dismissed

2023-11-13 20:30 UTC, ncontinanza approved these changes

2023-11-14 14:07 UTC, AngieDutra approved these changes
Nice work!

2023-11-14 14:41 UTC, ncontinanza approved these changes

2023-11-14 14:41 UTC, merged