Players can choose their name
lambdaclass/curse_of_myrra pull request #1040
Opened 2023-10-24 19:35 UTC by ncontinanza

2023-10-25 19:44 UTC, BertovDev requested changes
I tested the functionality its nice! and i have some comments that i believe they will improve much more this:

- Player name should be shown somewhere in the screen. So you know which one you have selected.
- Input placeholder should show the current name you have: example: If i change the name to `Berto` and then i wanted to change it again the placeholder shouldnt say Player Name
<img width="333" alt="Captura de pantalla 2023-10-25 a la(s) 16 36 25" src="https://github.com/lambdaclass/curse_of_myrra/assets/62818001/009be9f0-9ea6-472f-8338-123a35e95d84">

- Name length should be restricted to a certain amount of characters. If not i can type infinite and the UI will be broken.

- When I enter a game and then disconnect and reconnect an error is been displayed and the name reset to player {id}
<img width="839" alt="Captura de pantalla 2023-10-25 a la(s) 16 30 58" src="https://github.com/lambdaclass/curse_of_myrra/assets/62818001/9a98606f-107c-4edd-ba8c-86ac2379bc4a">



I have notice this issues just playing around with it, I didnt check any code yet.
What do you think about what I commented?

2023-10-26 21:02 UTC, saugon commented
There are some fix proposals that have arisen from playtesting:

- [ ] Add padding space between the text input and the error message.
Enhance players' names in battle (the ones that appear above the players' characters):
  - [ ] Increase the size of the name box to prevent two-line names.
  - [ ] Set a maximum character name size.
  - [ ] Reduce the font size.
- [ ] The placeholder shouldn't be included in the input value (when tapping the input, it's annoying to have to erase it).

2023-10-30 15:01 UTC, BertovDev reviewed
Looks awesome to me and i will only add a method called `GetPlayerNameById` but only if this functionality will persevere in the future (since we will use another way of storing the names)

2023-10-30 15:13 UTC, AngieDutra requested changes
<img width="161" alt="Captura de pantalla 2023-10-30 a las 11 56 13 a  m" src="https://github.com/lambdaclass/curse_of_myrra/assets/82987608/6767601b-8e09-4d0a-b0fb-9b7e4acf0438">

The input text should be uppercase.

2023-11-01 14:57 UTC, ncontinanza commented on client/Assets/Scenes/Lobbies.unity
Done!

2023-11-01 15:01 UTC, ncontinanza commented
> The input text should be uppercase.

That is the user's input, right? Currently the user is able to use lowercase, and we change it to uppercase afterwards. If you submit a name that contains lowercase letters, you should have it converted to uppercase everywhere, including that placeholder the next time you click on the change name button.

2023-11-01 21:09 UTC, BertovDev submitted a review, later dismissed
Love this PR!

2023-11-02 20:53 UTC, AngieDutra commented
> > The input text should be uppercase.
> 
> That is the user's input, right? Currently the user is able to use lowercase, and we change it to uppercase afterwards. If you submit a name that contains lowercase letters, you should have it converted to uppercase everywhere, including that placeholder the next time you click on the change name button.

I commented on it from a design POV. We are using that font only in uppercase format. If uppercase is not intended in this input I would recommend changing the font.

2023-11-02 21:26 UTC, saugon commented
> > > The input text should be uppercase.
> > 
> > 
> > That is the user's input, right? Currently the user is able to use lowercase, and we change it to uppercase afterwards. If you submit a name that contains lowercase letters, you should have it converted to uppercase everywhere, including that placeholder the next time you click on the change name button.
> 
> I commented on it from a design POV. We are using that font only in uppercase format. If uppercase is not intended in this input I would recommend changing the font.

This is a valid observation. I wouldn't change the font but would display the text always in uppercase characters.
In any case, I'd set this aside for now and address it in a future PR if needed.

2023-11-03 14:52 UTC, BertovDev approved these changes

2023-11-03 16:00 UTC, AngieDutra approved these changes
This PR is awesome ✨ LGTM

2023-11-03 16:00 UTC, merged