Update README with environment suggestions
lambdaclass/curse_of_myrra pull request #1056
Opened 2023-10-25 23:05 UTC by martinacantaro

To help onboard new teammembers, especially now that there's rotations.

2023-10-26 17:38 UTC, ncontinanza requested changes

2023-10-26 17:38 UTC, ncontinanza commented on README.md
> +- In VSCode's console, select the Output tab and pick Omnisharp Log in the dropdown.
This is not a requirement, but a way of checking that the previous steps worked. If you don't get logs in that tab and you see that Omnisharp is scanning the project, then the config is OK. 
I would rephrase it or leave it separately as a note, so that it doesn't seem as it is a part of the environment set up, what do you think?

2023-10-27 14:29 UTC, martinacantaro commented on README.md
> +- In VSCode's console, select the Output tab and pick Omnisharp Log in the dropdown.
Cool! Makes sense!

2023-10-27 14:39 UTC, ncontinanza approved these changes
LGTM!

2023-10-27 15:40 UTC, Nico-Sanchez approved these changes

2023-10-27 15:44 UTC, ncontinanza approved these changes

2023-10-27 15:45 UTC, merged