Character list
lambdaclass/curse_of_myrra pull request #1061
Opened 2023-10-26 19:51 UTC by AngieDutra

This PR closes issue #926 
![Refe-1](https://github.com/lambdaclass/curse_of_myrra/assets/82987608/0130fec5-05c3-41c2-9378-df3024472b4e)

Check:
- you can go from MainScreen to this screen and back to Main
- the list scrolls as expected
- the information is right

2023-10-27 15:38 UTC, Nico-Sanchez requested changes
The character list scene looks good. Nice job!

Left some comments regarding the code and an error I had when testing it.

2023-10-27 15:38 UTC, Nico-Sanchez commented on client/ProjectSettings/EditorBuildSettings.asset
> +  - enabled: 0
I had an error with the character list scene and had to enable it from Unity.

I believe if you enable it here that error will be fixed. Can we do that or this is zero on purpose?

2023-10-27 15:38 UTC, Nico-Sanchez commented on client/Assets/Scripts/UI/CharactersListManager.cs
> +            //item.GetComponentInChildren<TextMeshPro>().text = player.name;
Can we remove this comment? Do we want to keep this?

2023-10-27 15:42 UTC, AngieDutra commented on client/Assets/Scripts/UI/CharactersListManager.cs
> +            //item.GetComponentInChildren<TextMeshPro>().text = player.name;
On it!

2023-10-27 15:49 UTC, Nico-Sanchez submitted a review, later dismissed

2023-10-27 16:00 UTC, BertovDev requested changes

2023-10-27 16:00 UTC, BertovDev commented on client/Assets/Scripts/UI/CharactersListManager.cs
> +            item.GetComponentInChildren<TextMeshProUGUI>().text = player.name;
```suggestion
        CharactersScriptables.ForEach(character =>
        {
            GameObject item = Instantiate(listItem, this.transform);
            item.GetComponentInChildren<Image>().sprite = character.characterSprite;
            item.GetComponentInChildren<TextMeshProUGUI>().text = character.name;
```

2023-10-27 22:01 UTC, AngieDutra commented on client/Assets/Prefabs/UI/CharacterListItem.prefab
Talked with our TL and agreed it wasn't wrong to do it in order to solve design issues. With that being said design changes were made and functionality changes resulted in this not being an issue anymore

2023-10-27 22:01 UTC, AngieDutra commented on client/Assets/Scripts/UI/CharactersListManager.cs
> +    List<CoMCharacter> players;
I agree on this but changed it to CharacterScriptableObjects

2023-10-27 22:02 UTC, AngieDutra commented on client/Assets/Scripts/UI/CharactersListManager.cs
> +            item.GetComponentInChildren<TextMeshProUGUI>().text = player.name;
This was already adressed

2023-10-30 18:38 UTC, BertovDev requested changes
Characters Button in mainScreen is not working.

2023-10-30 18:49 UTC, AngieDutra commented
> Characters Button in mainScreen is not working.

Are you sure? I'm testing it and it works just fine to me. Make sure to update your branch and to close and open the Unity project

2023-10-31 14:29 UTC, BertovDev submitted a review, later dismissed

2023-11-01 18:32 UTC, tvillegas98 approved these changes
LGTM!

2023-11-01 19:12 UTC, AngieDutra commented
> I dont quite understand the `IsBackButton` functionality in `ButtonAnimationsMMTouchButton` can you please bring a little more explanation about it.

Sure! isBackButton is useful to identify back buttons. Although these should have the same looking scale animation due to its different size the scale difference should be bigger. It is also helpful to identify the buttons that trigger a change of scene to avoid the error of animating an element that is no longer there. I believe there is room for improvement tho, but this was the first implementation

2023-11-01 19:17 UTC, BertovDev commented
> > I dont quite understand the `IsBackButton` functionality in `ButtonAnimationsMMTouchButton` can you please bring a little more explanation about it.
> 
> Sure! isBackButton is useful to identify back buttons. Although these should have the same looking scale animation, due to its different size the scale difference should be bigger to be noticeable. It is also helpful to identify the buttons that trigger a change of scene to avoid the error of animating an element that is no longer there. I believe there is room for improvement tho, but this was the first implementation

Nice!, thanks for the explanation

2023-11-01 19:17 UTC, BertovDev approved these changes
Nice!

2023-11-01 19:17 UTC, merged