Add 3D sound to spawn sfx
lambdaclass/curse_of_myrra pull request #1076
Opened 2023-10-30 16:53 UTC by tkz00

Changes the way the spawn sfx is played for the characters the player isn't controlling, instead of using the normal sound manager, it uses the prefabs Sound3DManager.

This is kind of tricky to test since the spawn sounds are played all at the same time, but to check this worked fine I added this method to `CustomLevelManager.cs`:

```
IEnumerator ActivateSpawnFeedbackWithDelay(List<CustomCharacter> characters)
    {
        foreach (var character in characters)
        {
            yield return new WaitForSeconds(1);
            StartCoroutine(character.characterBase.activateSpawnFeedback(false));
        }
}
```

and changed the method `CameraCinematic` to:

```
IEnumerator CameraCinematic()
    {
        if (!SocketConnectionManager.Instance.cinematicDone)
        {
            //Start moving camera and remove loading sceen
            InvokeRepeating("Substract", 1f, 0.1f);
            yield return new WaitForSeconds(1.7f);
            loadingScreen.SetActive(false);
            battleScreen.SetActive(true);
            //Cancel camera movement and start zoom in
            List<CustomCharacter> notPlayerCharacters = Utils
                .GetAlivePlayers()
                .Where(player => player.Id != playerId)
                .Select(player => Utils.GetCharacter(player.Id))
                .ToList();
            StartCoroutine(ActivateSpawnFeedbackWithDelay(notPlayerCharacters));
            StartCoroutine(
                Utils.GetCharacter(
                        playerId)
                    .characterBase.activateSpawnFeedback(true));
            yield return new WaitForSeconds(2.1f);
            CancelInvoke("Substract");
            InvokeRepeating("MoveYCamera", 0.3f, 0.1f);
            //Cancel camera zoom
            yield return new WaitForSeconds(0.5f);
            CancelInvoke("MoveYCamera");
        }
        else
        {
            cameraFramingTransposer.m_TrackedObjectOffset = new Vector3(0, 0, 0);
            yield return new WaitForSeconds(0.9f);
            loadingScreen.SetActive(false);
        }
}

```

Then you have to check you only hear one spawn effect when no other player spawns near you, and more spawn sounds when other players spawn within your screen, you can also increment the Max Distance property of the MMSoundManager Sound feedback in the MMF Player component of the 3DSoundManager child component of the CharacterBase prefaf, this increases the distance where the sound can be heard, avoiding having to test so many times to spawn next to one another. 

Closes #1073

2023-11-07 14:10 UTC, ncontinanza requested changes
It seems like in the last merge the out of area feedback was removed from each character's prefab. Everything else was working fine!

2023-11-08 18:31 UTC, tkz00 commented
> It seems like in the last merge the out of area feedback was removed from each character's prefab. Everything else was working fine!

Fixed it!

2023-11-13 19:46 UTC, ncontinanza approved these changes

2023-11-16 18:07 UTC, BertovDev approved these changes

2023-11-17 14:02 UTC, ncontinanza approved these changes

2023-11-17 14:02 UTC, merged