Dynamic position for basic skill
lambdaclass/curse_of_myrra pull request #1080
Opened 2023-10-31 13:12 UTC by AngieDutra

This PR closes #1072 
This PR changes the basic skill input positioning. To test it the reviewer should be able to use the basic skill pressing anywhere from the middle to the right side of the screen. The only exceptions of use are when pressing the other two inputs (skill1 and crate).

2023-11-07 15:03 UTC, BertovDev commented
increase cancel Area of the button. Now its so difficult to hit the cancel.

2023-11-09 23:02 UTC, saugon commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +        if (value.x < 0.5f && value.x > -0.5f && value.y < 0.5f && value.y > -0.5f)
The value 0.5f should be declared as a constant to enhance maintenance and readability, as well as to avoid the use of magic numbers.

2023-11-09 23:08 UTC, saugon commented on client/Assets/Scripts/UI/CustomMMTouchRepositionableJoystick.cs
> +        if (KnobCanvasGroup.GetComponent<CustomMMTouchJoystick>().isActiveAndEnabled)
There are many calls to GetComponent in this script that could potentially be enhanced, perhaps by utilizing an attribute that can be set in the Start method.

2023-11-10 14:51 UTC, AngieDutra commented on client/Assets/Scripts/UI/CustomMMTouchRepositionableJoystick.cs
> +        if (KnobCanvasGroup.GetComponent<CustomMMTouchJoystick>().isActiveAndEnabled)
Both comments were fixed!

2023-11-10 14:52 UTC, AngieDutra commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +        if (value.x < 0.5f && value.x > -0.5f && value.y < 0.5f && value.y > -0.5f)
Done!

2023-11-10 19:25 UTC, BertovDev requested changes
Loading GO in CameraUI prefab is inactive.

2023-11-10 19:25 UTC, BertovDev commented on client/mono_crash.mem.4740.1.blob
Delete This

2023-11-13 14:48 UTC, tkz00 requested changes
The variable previousDrag in CustomMMTouchJoystick is unused and should be deleted. Also in this script the variable scaleCanvas is only used inside the RefreshMaxRangeDistance method so it should be a method-local variable and contained only within that scope, not the classes one.

2023-11-13 21:54 UTC, AngieDutra commented
> scaleCanvas

In some cases this was useful. Also helped me notice one scaleCanvas wasn't being applied when it should have

2023-11-13 21:55 UTC, AngieDutra commented on client/mono_crash.mem.4740.1.blob
I did! Both things were fixed, thanks

2023-11-14 12:32 UTC, tkz00 submitted a review, later dismissed
Looks great! Nice work!

2023-11-14 19:37 UTC, BertovDev submitted a review, later dismissed
This is working so clean, congrats! just minor code changes/improvements that i believe that might be fine

2023-11-14 19:37 UTC, BertovDev commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +    const float cancelAreaValue = 0.5f;
We should follow the standar for Constants. This should be `CANCEL_AREA_VALUE`

2023-11-14 19:37 UTC, BertovDev commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +    public void CancelAttack(Vector2 value, bool dragged)
You dont need this parameters since their are field of the class. You can access `RawValue` and `dragged` without passing it by parameter.

2023-11-14 19:37 UTC, BertovDev commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +        CancelAttack(RawValue, dragged);
Remove this parameters

2023-11-14 19:37 UTC, BertovDev commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +        CancelAttack(RawValue, dragged);
Remove this parameters

2023-11-14 19:37 UTC, BertovDev commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +        float scaleCanvas = GetComponentInParent<Canvas>().gameObject.transform.localScale.x;
`float scaleCanvas = GetComponentInParent<Canvas>().gameObject.transform.localScale.x;`

.gameObject is not necessary here you can simply do: 
`GetComponentInParent<Canvas>().transform.localScale.x;`

2023-11-14 19:37 UTC, BertovDev commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +            gameObject.transform.parent.GetComponent<RectTransform>().rect.width / 2;
Same here `.gameObject` not necessary.

2023-11-14 19:37 UTC, BertovDev commented on client/Assets/Scripts/UI/CustomMMTouchRepositionableJoystick.cs
> +        scaleCanvas = GetComponentInParent<Canvas>().gameObject.transform.localScale.x;
This Scripts looks awesome just delet unecessary `.gameObject`.

`GetComponentInParent<Canvas>().gameObject.transform.localScale.x;`
 to
`GetComponentInParent<Canvas>().transform.localScale.x;`

2023-11-14 19:49 UTC, AngieDutra commented on client/Assets/Scripts/CustomInputManager.cs
> +        _player.GetComponentInChildren<AimDirection>().DeactivateIndicator();
I used directionIndicator to tackle this. The rest I believe a refactor is needed since I can access AimDirection in more than one way

2023-11-14 19:49 UTC, AngieDutra commented on client/Assets/Scripts/CustomInputManager.cs
> +            SetSkillRangeCancelable(value);
done!

2023-11-14 19:50 UTC, AngieDutra commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +    const float cancelAreaValue = 0.5f;
Agree! changed it

2023-11-14 19:56 UTC, AngieDutra commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +        CancelAttack(RawValue, dragged);
done

2023-11-14 19:56 UTC, AngieDutra commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +        CancelAttack(RawValue, dragged);
done

2023-11-14 19:57 UTC, AngieDutra commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +        float scaleCanvas = GetComponentInParent<Canvas>().gameObject.transform.localScale.x;
cool, done

2023-11-14 19:57 UTC, AngieDutra commented on client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
> +            gameObject.transform.parent.GetComponent<RectTransform>().rect.width / 2;
done

2023-11-14 19:58 UTC, AngieDutra commented on client/Assets/Scripts/UI/CustomMMTouchRepositionableJoystick.cs
> +        scaleCanvas = GetComponentInParent<Canvas>().gameObject.transform.localScale.x;
done

2023-11-14 20:46 UTC, tkz00 approved these changes
Looks great!

2023-11-14 20:57 UTC, ncontinanza approved these changes
LGTM!

2023-11-14 20:58 UTC, merged