Character info screen
lambdaclass/curse_of_myrra pull request #1088
Opened 2023-11-01 19:07 UTC by BertovDev

Closes #[issue]

## Motivation

We needed to implement the character info screen where you can see all characters information and select it fo the future game flow.

## Summary of changes

- Implement a new Scene, CharacterInfo
- Scrips:
	- Created `CharacterInfoManager`
	- Changed `MainScreenModelManager` to `UIModelManager`
	- Changed `SkillDescription`
- Changed `CharactersListCameraUI` title

## How has this been tested?

1. Start the game in te MainScreen scene.
2. Click in characters
3. Select any character, you should see the character info screen of the selected character
4. Click the abilities and see if their change
5. Click the left and right arrows and see the characters change
6. Use the back button and repetear the process

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-11-02 19:32 UTC, BertovDev commented
TODO:
Character list:
- [ ] El primer tap a las tarjetas no funciona.
- [ ] Una vez que hiciste tap, si querés scrollear te ejecuta directamente el tap
- [ ] Bloquear interacción con la tarjeta de Valtimer
- [ ] Corregir el title
- [ ] Agregar padding inferior al scroll
Character info:
- [ ] Usar los botones de lore y overview transparentes.
- [ ] General:
- [ ] Que todo lo tapeable tenga el efecto de dotween
- [ ] Sumar tooltips y headers donde corresponda
- [ ] Borrar codigo no usado (SkillType)
- [ ] Cambiar Ability por Skill
- [ ] Renombrar currentPos y startPos

2023-11-06 14:27 UTC, tkz00 requested changes
When you touch in a character in the character selection screen, most of the times it doesn't take you to the CharacterInfo scene, nothing happens, my guess is that it has something to do with the fix to the scroll functionality you implemented, since before that, this bug wasn't there, but it could be something else. This error only happened to me in Android, in PC it works fine, didn't test in iOS.

https://github.com/lambdaclass/curse_of_myrra/assets/67983386/7e695cac-8f8d-49bb-af7b-2ab57e7019d7

2023-11-06 15:32 UTC, BertovDev commented
> When you touch in a character in the character selection screen, most of the times it doesn't take you to the CharacterInfo scene, nothing happens, my guess is that it has something to do with the fix to the scroll functionality you implemented, since before that, this bug wasn't there, but it could be something else. This error only happened to me in Android, in PC it works fine, didn't test in iOS.
> Screen_Recording_20231106_111203_client.mp4

Nice catch! The problem here is that in phones the touchStartPos and the eventData.position are never equals their always have a minimun difference. I will push the fix.

2023-11-06 15:58 UTC, tkz00 approved these changes
Great, works wonderfully now!

2023-11-06 17:17 UTC, saugon commented
I've identified some of issues that need fixing/improvement:

- [ ] There seems to be no order correlation between the character list and the navigation within the character info. According to Character list order, it should be: H4ck -> Dagna -> Muflus -> Uma.

https://github.com/lambdaclass/curse_of_myrra/assets/6811225/60c89611-34d6-4c05-9de9-bc1a448978c4


- [ ] On a few occasions while viewing Muflus's screen, pressing the 'left button' caused it to switch rapidly from H4ck to Uma. I couldn't reproduce it again,(I'll attempt to do so. 
- [ ] The position of the character info navigation bar should align with that in the character list.

https://github.com/lambdaclass/curse_of_myrra/assets/6811225/c14a8a64-755f-4e72-9129-7dc77134e78b

2023-11-09 13:51 UTC, tkz00 requested changes
When you press one of the character's portrait inside character list sometimes another portrait also plays the animation of being pressed as well. I'm trying to upload a video but I can't, don't really know why.

2023-11-10 19:35 UTC, tkz00 submitted a review, later dismissed
LGTM! Great work!

2023-11-14 19:31 UTC, AngieDutra requested changes
I noticed in the character info you have 2 basic skills when you should have a Basic skill and a Super skill. Please change that
<img width="159" alt="Captura de pantalla 2023-11-14 a la(s) 16 22 41" src="https://github.com/lambdaclass/curse_of_myrra/assets/82987608/a5042e62-ccd7-4a90-ad2f-4721c9df5816">

<img width="153" alt="Captura de pantalla 2023-11-14 a la(s) 16 22 33" src="https://github.com/lambdaclass/curse_of_myrra/assets/82987608/122dfb2a-a17b-495f-8a81-bad933d48ee9">

In addition, I checked with the design team and the texts under the character's name should be in one line.
<img width="110" alt="Captura de pantalla 2023-11-14 a la(s) 16 22 13" src="https://github.com/lambdaclass/curse_of_myrra/assets/82987608/021414c1-e219-4c49-a6ac-53dd823d8c13">
Finally I recommend re-reading our teams recommendations to set images in unity. Max Sizes in the sprites you added are not as they should be

2023-11-14 19:31 UTC, AngieDutra commented on client/Assets/Images/UI/3-Icon.png
Images like this should have been set in Unity to a max size of 512 and not 2048 as they currently are
<img width="413" alt="Captura de pantalla 2023-11-14 a la(s) 16 24 51" src="https://github.com/lambdaclass/curse_of_myrra/assets/82987608/666239bc-598a-469d-8fb2-46cf48be5da6">

2023-11-14 20:47 UTC, AngieDutra requested changes
<img width="1440" alt="Captura de pantalla 2023-11-14 a la(s) 16 16 44" src="https://github.com/lambdaclass/curse_of_myrra/assets/82987608/7c2f06da-bed6-4b7d-9d38-529f00418939">
The unavailable characters shouldn't have a selected animation. These buttons should be disabled

2023-11-14 21:07 UTC, AngieDutra approved these changes
Amazing! ✨

2023-11-16 16:13 UTC, AngieDutra requested changes
I reviews once again the images and didn't saw all the changes I was expecting from the previous review I gave. Please check all the sprites and the notion recommendations. Since you are focusing on this I will also add a request: We are implementing folders to organize the sprites. In our notion you will find our criteria for that specifically

2023-11-16 16:13 UTC, AngieDutra commented on client/Assets/Images/UI/Arrow.png
This one still has Max Size 2048

2023-11-16 16:13 UTC, AngieDutra commented on client/Assets/Images/UI/Lore-Icon-disabled.png
I have a suggestion here. Instead of using two assets, one for the disable and one for the enable state, since the only difference is the opacity level I suggest adding a CanvasGroup component and changing the alpha value to 0.25. Therefore, delete this file

2023-11-16 16:13 UTC, AngieDutra commented on client/Assets/Images/UI/Lore-Icon.png
This one still has Max Size 2048

2023-11-16 16:13 UTC, AngieDutra commented on client/Assets/Images/UI/Not press.png
This one still has Max Size 2048

2023-11-16 16:13 UTC, AngieDutra commented on client/Assets/Images/UI/Overview-Icon-disabled.png
Delete this file

2023-11-16 16:13 UTC, AngieDutra commented on client/Assets/Images/UI/Press.png
This one still has Max Size 2048

2023-11-16 16:13 UTC, AngieDutra commented on client/Assets/Images/UI/shadow-character.png
You imported this file but you haven't set this properly as a Sprite in Unity.nIn addition, I don't see it used in the UI and I believe you should

2023-11-17 14:23 UTC, ncontinanza submitted a review, later dismissed
Great job!

2023-11-17 16:15 UTC, AngieDutra requested changes
I believe that in every character the Basic is supposed to show first and in Umma's case that is not happening.
<img width="158" alt="Captura de pantalla 2023-11-17 a las 13 10 01 p  m" src="https://github.com/lambdaclass/curse_of_myrra/assets/82987608/db2b95b6-d981-4d3b-b53d-1dd871bc056c">

2023-11-21 14:37 UTC, AngieDutra approved these changes
This PR is awesome! Congrats ✨

2023-11-21 15:27 UTC, ncontinanza approved these changes
Great job!

2023-11-21 15:27 UTC, merged