[GH-917] Character visual feedback in damage zone
lambdaclass/curse_of_myrra pull request #1089
Opened 2023-11-01 19:09 UTC by tkz00

Closes #917 

## Motivation

Apart from the characters model flashing repeatedly there was no visual feedback to indicate a player was receiving damage when out of bounds, when the character that is out of bounds is the one we are controlling we would get a screen filter as a visual feedback, but that wasn't enough and also it was unclear if enemies were taking damage since this canvas filter didn't apply to them. This PR aims to solve that issue by adding a red particle effect to all characters when in the damage zone.

## Summary of changes

Created a new state feedback prefab called OutOfArea and added it to the FeedbackContainer. Referenced this component in the feedbacksStatesPrefabs list of the CharacterFeedbacks script inside each of the characters prefabs.

## How has this been tested?

In a match with two players, one of the clients with this PR's branch in my pc and the other in my phone with the testing branch, moved both the phone and pc characters into the damage zone and checked the desired particle effects where displayed in my pc's client.

## Test additions / changes

No changes or additions were made to the tests in this PR.

## Checklist
- [X] I have tested the changes locally.
- [X] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-11-01 20:42 UTC, BertovDev requested changes
Nice effect! and only one thing to correct.

1. When player dies in the zone the feedback is still playing. This can be easy fixed doing the following:
In the `SetPlayerDead` method in `Battle.cs` add the following code:
```
 playerCharacter
            .GetComponent<CharacterFeedbacks>()
            .ClearAllFeedbacks(playerCharacter.gameObject);
```

2023-11-01 21:16 UTC, tkz00 commented
> Nice effect! and only one thing to correct.
> 
>     1. When player dies in the zone the feedback is still playing. This can be easy fixed doing the following:
>        In the `SetPlayerDead` method in `Battle.cs` add the following code:
> 
> 
> ```
>  playerCharacter
>             .GetComponent<CharacterFeedbacks>()
>             .ClearAllFeedbacks(playerCharacter.gameObject);
> ```

You are right, already made the changes!

2023-11-01 21:27 UTC, BertovDev commented
> > Nice effect! and only one thing to correct.
> > ```
> > 1. When player dies in the zone the feedback is still playing. This can be easy fixed doing the following:
> >    In the `SetPlayerDead` method in `Battle.cs` add the following code:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >  playerCharacter
> >             .GetComponent<CharacterFeedbacks>()
> >             .ClearAllFeedbacks(playerCharacter.gameObject);
> > ```
> 
> You are right, already made the changes!

Cool and you also avoid multiple GetComponent<> calls with this add. Nice!!

2023-11-01 21:27 UTC, BertovDev approved these changes

2023-11-01 21:29 UTC, BertovDev requested changes
Monocrash😞

2023-11-01 21:29 UTC, BertovDev commented on client/mono_crash.mem.92026.1.blob
Delte this

2023-11-02 16:01 UTC, BertovDev submitted a review, later dismissed

2023-11-06 13:52 UTC, BertovDev approved these changes
LGTM!

2023-11-06 14:43 UTC, ncontinanza approved these changes

2023-11-06 14:43 UTC, merged