Gh 1116 disable error popup and relocate in game performance metrics
lambdaclass/curse_of_myrra pull request #1120
Opened 2023-11-10 15:36 UTC by tkz00

Closes #1116

## Motivation

The position of the in-game metrics was being covered in iOS by a system bar that appears in the bottom of the screen, so it had to be moved to the top. The version error popup was disrupting the game flow and doesn't currently make the verification correctly, it always appeared even if the game was playable, and the reconnect functionality isn't working as intended either so the popup had to be disabled temporarily.

## Summary of changes

Moved the game metric element to the top of the battle UI, also had to vertically mirror the metrics container image so it looked correctly on top of the screen, and disabled the call to the coroutine that checks for ongoing player games as well as the logic that makes the version error popup appear, both of them in the `LobbyConnection.cs` script.

## How has this been tested?

- For the in-game metrics display enter a game and in the battle scene you should see the fps, ping ms, and version hashes on top of the screen instead of the bottom.

- For the popups that don't have to appear enter a game and get out both by force quitting the game (stop playing in Unity or close the application in mobile) and check when you enter to the lobbies scene again the reconnect popup doesn't appear. Also check the version match error popup doesn't appear in the lobbies scene when you enter it or try to create a lobby.

## Test additions / changes

No tests were added or changed

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-11-16 19:42 UTC, BertovDev requested changes

2023-11-16 19:42 UTC, BertovDev commented on client/Assets/Scenes/Battle.unity
Changes should be made in `CameraUI` prefab and not the scene. 
You can aplly all the changes of the prefab in the scene and then checkout the changes with:

`git checkout main -- client/Assets/Scenes/Battle.unity` to restore the Battle Scene

2023-11-16 19:42 UTC, BertovDev commented on client/Assets/Scripts/LobbyConnection.cs
> +        // }
We want to keep this code if it is not been use? 

What do you think?, let me know.

2023-11-17 18:15 UTC, tkz00 commented on client/Assets/Scenes/Battle.unity
Right! I'll let you know when I make the change.

2023-11-17 18:30 UTC, tkz00 commented on client/Assets/Scenes/Battle.unity
All ready!

2023-11-21 13:58 UTC, BertovDev approved these changes
LGTM

2023-11-21 13:58 UTC, BertovDev commented on client/Assets/Scripts/LobbyConnection.cs
> +        // }
Nice! seems correct

2023-11-21 14:48 UTC, ncontinanza approved these changes

2023-11-21 14:48 UTC, merged