Remove TopDown engine from repository
lambdaclass/curse_of_myrra pull request #1121
Opened 2023-11-10 19:01 UTC by tkz00

Closes #1112 

## Motivation & Summary of Changes

Since TopDown Engine is an external dependency we removed it from the repository.

## Checklist
- [X] I have tested the changes locally.
- [X] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [X] This change requires new documentation.
  - [X] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-11-13 19:23 UTC, manucamejo commented
Nice work @tkz00, I have some questions:
- How can I run from scratch if I don't have TopDownEngine installed? Did you try it? Can you document it?
- Is it going to crash when we merge it? We have to do something?

2023-11-13 20:38 UTC, tkz00 commented
> Nice work @tkz00, I have some questions:
> 
>     * How can I run from scratch if I don't have TopDownEngine installed? Did you try it? Can you document it?
> 
>     * Is it going to crash when we merge it? We have to do something?

Everyone on the team should have no problems running and working on the game when we merge, since the TopDownEngine folder was removed from the repository and added to the gitignore so it will not affect the "local" TopDownEngine folders we have. If someone clones the project from scratch he will need to add the engine's folder to the correct location inside the project. This has been specified in the readme, but take a look at it and let me know if the instructions look clear or if you would change or add something!

2023-11-16 18:12 UTC, BertovDev commented
> > Nice work @tkz00, I have some questions:
> > ```
> > * How can I run from scratch if I don't have TopDownEngine installed? Did you try it? Can you document it?
> > 
> > * Is it going to crash when we merge it? We have to do something?
> > ```
> 
> Everyone on the team should have no problems running and working on the game when we merge, since the TopDownEngine folder was removed from the repository and added to the gitignore so it will not affect the "local" TopDownEngine folders we have. If someone clones the project from scratch he will need to add the engine's folder to the correct location inside the project. This has been specified in the readme, but take a look at it and let me know if the instructions look clear or if you would change or add something!

IMO, further documentation should be added on how to setup the engine, something like:

- Where it is going to be placed the engine to be downloaded?

2023-11-16 18:12 UTC, BertovDev commented on README.md
> +- It's also needed to download the [Top Down Engine](https://assetstore.unity.com/packages/templates/systems/topdown-engine-89636) by [More Mountains](https://moremountains.com) and include it in the
I believe you should include in the asset folder but inside ThirdParty

`Assets/ThirdParty`

2023-11-16 18:19 UTC, tkz00 commented on README.md
> +- It's also needed to download the [Top Down Engine](https://assetstore.unity.com/packages/templates/systems/topdown-engine-89636) by [More Mountains](https://moremountains.com) and include it in the
Nice catch, I'll modify the readme.

2023-11-17 15:06 UTC, ncontinanza requested changes
Please elaborate a bit more on how to import the TopDown engine folder for testing this PR

2023-11-21 13:17 UTC, tkz00 commented
> Please elaborate a bit more on how to import the TopDown engine folder for testing this PR

Already expanded the documentation!

2023-11-21 18:50 UTC, BertovDev approved these changes
Nice

2023-11-21 19:10 UTC, ncontinanza approved these changes
Working good! Tested it locally and in an Android device

2023-11-21 19:12 UTC, merged