Main screen updates
lambdaclass/curse_of_myrra pull request #1154
Opened 2023-11-16 23:29 UTC by AngieDutra

Closes #1042 

## Motivation

A change of style was needed for UI-UX porpouses

## Summary of changes
![reference](https://github.com/lambdaclass/curse_of_myrra/assets/82987608/1826b7bb-b8f6-4a7b-a316-3a6cfd175e90)

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-11-17 20:52 UTC, manucamejo commented
@AngieDutra I've 2 questions:
If I change the server, the "box" fits the word, is that correct? Or should we have the box width for all the different server names?
<img width="284" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/20927859/b46f39e8-7f85-40a7-85cb-6cc2f215b934">
<img width="368" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/20927859/3eb2d011-9438-4bec-8304-5ebd5d0776ee">


Also, the UI is different than the PR description, is that ok?
<img width="339" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/20927859/9a1ae034-6bcb-45d9-8628-2c1073117b4b">

2023-11-17 21:20 UTC, AngieDutra commented
> @AngieDutra I've 2 questions: If I change the server, the "box" fits the word, is that correct? Or should we have the box width for all the different server names? <img alt="image" width="284" src="https://user-images.githubusercontent.com/20927859/283928737-b46f39e8-7f85-40a7-85cb-6cc2f215b934.png"> <img alt="image" width="368" src="https://user-images.githubusercontent.com/20927859/283929193-3eb2d011-9438-4bec-8304-5ebd5d0776ee.png">
> 
> Also, the UI is different than the PR description, is that ok? <img alt="image" width="339" src="https://user-images.githubusercontent.com/20927859/283929286-9a1ae034-6bcb-45d9-8628-2c1073117b4b.png">

The select button for the server is supposed to work that way. It adjusts to the server name.
The UI differences, if you refer to the transparent buttons, is because they are currently disabled. When we develop them I will enable them and the opacity will be like the image reference. If the differences you talked about were not about that, please tell me so

2023-11-17 21:22 UTC, manucamejo submitted a review, later dismissed

2023-11-21 13:13 UTC, tkz00 approved these changes
LGMT!

2023-11-21 17:59 UTC, BertovDev commented on client/Assets/Scenes/MainScreen.unity
Do we need this changes in this scene?

2023-11-21 18:03 UTC, AngieDutra commented on client/Assets/Scenes/MainScreen.unity
Yes we do because in main there are changes applied to the scene. Now it is all based on the prefab changes

2023-11-21 18:10 UTC, martinacantaro commented
A small obvservation: the `Play` button has a solid pink background, while the `daily quest`, `characters` and `news` buttons have a pink-black gradient.  I would add the gradient to the Play button as well, so that they all look coherent

2023-11-21 18:20 UTC, ncontinanza requested changes

2023-11-21 18:20 UTC, ncontinanza commented on client/Assets/Scripts/UI/ButtonAnimationsMMTouchButton.cs
> +        "If this component is applied to a back button this should be truw to avoid animation errors"
```suggestion
        "If this component is applied to a back button this should be true to avoid animation errors"
```

2023-11-21 18:22 UTC, AngieDutra commented
> A small obvservation: the `Play` button has a solid pink background, while the `daily quest`, `characters` and `news` buttons have a pink-black gradient. I would add the gradient to the Play button as well, so that they all look coherent

The button has a gradient between two similar magenta colors. Never the less, I spoke with the design team and they said a refactor on that is coming soon

2023-11-21 18:28 UTC, BertovDev approved these changes
Looks amazing!

2023-11-21 18:34 UTC, ncontinanza approved these changes

2023-11-21 18:34 UTC, merged