More metrics
lambdaclass/curse_of_myrra pull request #1162
Opened 2023-11-20 19:08 UTC by AminArria

## Motivation

We need more observability when running the load tests

## Summary of changes

- `new_relic_agent` dependency is fetched for all environments, but disabled in `config.exs` and only enable in `config/prod.exs`
- Add metrics for
  - Total player count
  - Total game count
  - Total websockets for games

2023-11-21 13:25 UTC, mFragaBA requested changes
I think we should also update the `bot_count` from the state on `handle_info({:spawn_bots, bot_count}, state)` at `engine_runner.ex`, since we're changing the amount of players in the game

2023-11-21 13:30 UTC, mFragaBA commented on server/lib/dark_worlds_server/engine/engine_runner.ex
> +    NewRelic.report_custom_metric("GameBackend/GameTickExecutionTime", now_after_tick - now)
oh, one small thing. Can we call this `GameTickExecutionTimeMs` to make the unit clear in newrelic?

2023-11-21 13:30 UTC, mFragaBA commented on server/lib/dark_worlds_server/engine/engine_runner.ex
> +    NewRelic.report_custom_metric("GameBackend/GameTickExecutionTime", now_after_tick - now)
```suggestion
    NewRelic.report_custom_metric("GameBackend/GameTickExecutionTimeMs", now_after_tick - now)
```

2023-11-21 13:51 UTC, fkrause98 commented on server/config/config.exs
> +config :new_relic_agent, license_key: nil
This line makes me raise an eyebrow, can we test that we're still reporting metrics in prod/load testing servers?.

2023-11-21 14:07 UTC, mFragaBA reviewed
perhaps we should document somewhere that in order to see the values of `TotalGames`, `TotalGamesWebSockets` and `TotalPlayers` in the metrics explorer you need to use the `count` option

<img width="397" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/25107475/ae2ef91b-fe39-48fd-aede-14f438bbfcb7">

What do you think?

2023-11-21 14:26 UTC, mFragaBA commented on server/config/config.exs
> +config :new_relic_agent, license_key: nil
it is doing so. You can check on the newrelic board and also it's [custom metrics](https://one.newrelic.com/nr1-core/data-explorer/metrics/MzkyNzY2M3xBUE18QVBQTElDQVRJT058MTM3MjcyODQxMQ?account=3927663&duration=3600000&state=bb2984f2-3f1b-a5c8-7c99-4b46d9a8b1cf)

2023-11-21 17:29 UTC, AminArria commented on server/config/config.exs
> +config :new_relic_agent, license_key: nil
This is from their [docs](https://github.com/newrelic/elixir_agent/tree/v1.27.8#disabling)

> If you want to disable the agent, you can do it in two different ways:
>
>Application config: config :new_relic_agent, license_key: nil
>Environment variables: NEW_RELIC_HARVEST_ENABLED=false

2023-11-21 17:51 UTC, AminArria commented on server/lib/dark_worlds_server/engine/engine_runner.ex
> +    NewRelic.report_custom_metric("GameBackend/GameTickExecutionTime", now_after_tick - now)
Done in 8f95664

2023-11-21 18:29 UTC, mFragaBA approved these changes
LGTM!

2023-11-22 15:24 UTC, fkrause98 approved these changes
LGTM!

2023-11-22 18:39 UTC, mFragaBA approved these changes
LGTM!

2023-11-22 18:39 UTC, mFragaBA commented
Let's wait before merging since @manucamejo wanted to review this

2023-11-23 13:15 UTC, merged