organize images in a grid
lambdaclass/curse_of_myrra pull request #1170
Opened 2023-11-22 15:24 UTC by martinacantaro

organize the four character images in a grid so that they occupy the space better, instead of being in a long column with too much blank space on the right

2023-11-22 21:45 UTC, Nico-Sanchez requested changes

2023-11-22 21:45 UTC, Nico-Sanchez commented on README.md
> +</p>
We should use two <p> tags. Doing so we'll have two rows of images instead of one.

2023-11-23 13:17 UTC, manucamejo approved these changes

2023-11-23 14:02 UTC, Nico-Sanchez approved these changes

2023-11-23 14:03 UTC, merged