Split starting game from started game
lambdaclass/curse_of_myrra pull request #1214
Opened 2023-11-28 15:19 UTC by agustinesco

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-11-29 22:26 UTC, mFragaBA commented on communication/messages.proto
> +    START_GAME = 3;
same as I commented in the backend PR. I think we are not using this one anymore

2023-11-30 14:12 UTC, mFragaBA requested changes
As talked with @saugon and @agustinesco, since we want to optimize scene loading times, we'll try keeping everything related to the battle in a single scene. That also means the preparing battle scene added in this PR since we can use that time to load the scene. 
For that we can introduce a new "preparing state" in the battle scene in which it doesn't listen for events. It just loads the scene and only when the game actually starts we can listen for new events

2023-12-01 14:52 UTC, mFragaBA commented
I tried this on both an android phone and on unity and it's getting pretty laggy

https://github.com/lambdaclass/curse_of_myrra/assets/25107475/87ff2527-f733-4e0e-9e29-4c8de317645e

2023-12-01 16:06 UTC, ncontinanza requested changes

2023-12-01 16:06 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +            InvokeRepeating("SendPlayerMovement", clientActionRate, clientActionRate);
```suggestion
            InvokeRepeating("SendPlayerMovement", 0, clientActionRate);
```

It's not necessary to wait the first time

2023-12-01 17:33 UTC, ncontinanza submitted a review, later dismissed
Looking great!

2023-12-01 18:53 UTC, mFragaBA approved these changes
LGTM! The slowdown issue has been fixed!

2023-12-01 20:14 UTC, ncontinanza approved these changes

2023-12-01 20:21 UTC, merged