Update README.md
lambdaclass/curse_of_myrra pull request #1218
Opened 2023-11-28 19:44 UTC by martinacantaro

- Added a table of contents
- Added links to our socials
- Added a better explanation of our licensing

Also made some minor wording improvements

2023-11-29 12:16 UTC, manucamejo approved these changes

2023-11-29 21:40 UTC, ncontinanza requested changes

2023-11-29 21:40 UTC, ncontinanza commented on README.md
> +- **Twitter:** [@YourTwitterHandle](https://twitter.com/curseofmyrra)
Should it be @curseofmyrra?

2023-11-30 17:39 UTC, ncontinanza approved these changes

2023-11-30 21:01 UTC, manucamejo approved these changes

2023-11-30 21:01 UTC, merged