Victory and death splash
lambdaclass/curse_of_myrra pull request #1234
Opened 2023-12-01 16:04 UTC by AngieDutra

## Motivation

The death splash needed a style refactor

## Summary of changes

This PR changes the style of the death splash

![defeated](https://github.com/lambdaclass/curse_of_myrra/assets/82987608/b311c8cf-def2-41e9-8429-e11ce9f74e5a)

![reference-win](https://github.com/lambdaclass/curse_of_myrra/assets/82987608/2f1335c0-098c-48bd-8e94-654563719367)

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2023-12-06 13:17 UTC, AngieDutra commented on client/Assets/Scripts/UI/KillFeedItem.cs
> +    Sprite muflusIcon,
Changes on this were pushed

2023-12-06 14:05 UTC, BertovDev requested changes
This PR contemplates get killed by the DangerZone? if it does im getting an error when i get kileld by it.
 It is trying to find a player with the dangerZone id. This happends in the method: `GetCharacterUIIcon` and then in `GetDefeaterSprite`

2023-12-06 16:17 UTC, AngieDutra commented on client/Assets/Scripts/CustomLevelManager.cs
> +            EndGameManager endGameManager = deathSplash.GetComponentInChildren<EndGameManager>();
done!

2023-12-06 16:25 UTC, AngieDutra commented on client/Assets/Scripts/UI/KillFeedManager.cs
> +                    Utils.GetPlayer(playerId).GetComponent<CustomCharacter>().CharacterModel.name
done!

2023-12-07 20:04 UTC, ncontinanza approved these changes
LGTM!

2023-12-07 20:04 UTC, merged