Skills refactor
lambdaclass/curse_of_myrra pull request #399
Opened 2023-06-28 15:29 UTC by saugon

2023-06-28 20:57 UTC, BertovDev requested changes
This is a really good job, there are some corrections to do in Muflus. But everything else looks clean! I will list the following the fixes to do in Muflus ( we can do it in another PR ).

- Set the min health to 100 in the health component ( To avoid damage feedback bugs )
- Add DamageFeedback Gameobject
- Add DeathFeedback Gameobject
- Fix DisplayName position

2023-06-28 20:57 UTC, BertovDev commented on client/Assets/Scripts/PlayerMovement.cs
> +        GameObject player = Utils.GetPlayer(SocketConnectionManager.Instance.playerId);
This `player` is not been used , right ? and its been assing in every frame. Should be deleted.

2023-06-28 20:57 UTC, BertovDev commented on client/Assets/Scripts/PlayerMovement.cs
> +        if (playerUpdate.CharacterName == "H4ck"){
This if is not working. It throw me an error  because `playerUpdate.CharacterName` return "H4ck" also using Muflus , it can be fixed by replacing it with :

`player.GetComponent<Character>().CharacterModel.name == "H4ck"`

2023-06-28 20:57 UTC, BertovDev commented on client/Assets/Scripts/PlayerMovement.cs
> +            GetComponent<PlayerFeedbacks>().DisplayDamageRecieved(player, healthComponent, playerUpdate.Health, playerUpdate.Id);
This is not necessary to be inside the if condition because it doesnt matter the type of character. It just need to have the `DamageFeedback` gameObject ( which is missing in Muflus)

2023-06-28 20:57 UTC, BertovDev commented on client/Assets/Scripts/PlayerMovement.cs
> +            GetComponent<PlayerFeedbacks>().ChangePlayerTextureOnDamage(player, healthComponent.CurrentHealth, playerUpdate.Health);
Same with this, dont need to be in the if statement , just need to have the `DeathFeedback `gameObject which is also missing.

2023-06-28 21:10 UTC, BertovDev commented on client/Assets/Scripts/PlayerMovement.cs
> +        if (playerUpdate.CharacterName == "H4ck"){
My bad , this return H4ck when you use Spawn a Bot using the Muflus Model ( For testing purposes) , so we can use` playerUpdate.CharacterName` but its not going to work if we want to test a Bot with muflus character

2023-06-29 15:22 UTC, saugon commented on client/Assets/Scripts/PlayerMovement.cs
> +            GetComponent<PlayerFeedbacks>().DisplayDamageRecieved(player, healthComponent, playerUpdate.Health, playerUpdate.Id);
Done! Thanks :)

2023-06-29 15:22 UTC, saugon commented on client/Assets/Scripts/PlayerMovement.cs
> +            GetComponent<PlayerFeedbacks>().ChangePlayerTextureOnDamage(player, healthComponent.CurrentHealth, playerUpdate.Health);
Done! Thanks :)

2023-06-29 17:17 UTC, ncontinanza approved these changes

2023-06-29 18:58 UTC, BertovDev approved these changes
Awesome!

2023-06-29 19:29 UTC, merged