Music and sfx
lambdaclass/curse_of_myrra pull request #479
Opened 2023-07-05 21:33 UTC by ncontinanza

Closes https://github.com/lambdaclass/curse_of_myrra/issues/322

This PR adds the Araban track to the Araban level, the sound effects related to H4ck and Muflus attacks, a mute/unmute button in the level scene and a volume controller in the pause screen.

Things to test:
- Start a new game in Araban with H4ck or Muflus, and verify that both the background music and the sfx are muted after starting.
- Use the toggle button in the right hand of the screen to unmute the music and sfx. Make sure that you can hear the background music, and the sound effects when attacking.
- Use the toggle button to mute the music and sfx. 
- Check that you can control the music volume in the pause screen.

2023-07-06 20:22 UTC, BertovDev requested changes
Nice work! I notice that Skill2 of muflus ( Rage ) dont have any sound feedback. Also I feel a little out of timming the Skill1 and Skill3 also in muflus.

Everything else works as expected, nice!

2023-07-06 20:34 UTC, BertovDev requested changes

2023-07-06 20:34 UTC, BertovDev commented on client/Assets/Scenes/BackendPlayground.unity
There is a Interpolation prefab in this scene out of the canvas. ( Maybe its a merge problem ). Also what else do you change in the scene?

2023-07-06 20:34 UTC, BertovDev commented on client/Assets/Scripts/Skills/Skill.cs
> +        Debug.Log("Sending action to backend");
Please remove the logs after merge.

2023-07-06 20:34 UTC, BertovDev commented on client/ProjectSettings/ProjectSettings.asset
Delete this if you can please.

2023-07-06 20:34 UTC, BertovDev commented on client/Assets/Scripts/UI/ToggleAudio.cs
This code looks so clean , nice!!

2023-07-07 14:24 UTC, ncontinanza commented on client/Assets/Scenes/BackendPlayground.unity
I added the background music (an MMF_Player object) and the mute/unmute button.

2023-07-07 14:30 UTC, ncontinanza commented
> Nice work! I notice that Skill2 of muflus ( Rage ) dont have any sound feedback. Also I feel a little out of timming the Skill1 and Skill3 also in muflus.

Talked to @saugon about this, we'll leave it like this by now.

2023-07-10 21:05 UTC, BertovDev approved these changes
Awesome!
I would turn down the music volume a little bit , something like 50% - 70% as default.

- [x] Tested in Unity Desktop
- [x] Tested in Android

2023-07-10 21:38 UTC, tvillegas98 approved these changes
LGTM!

2023-07-11 14:27 UTC, merged