Fix SocketConnectionManager Singleton
lambdaclass/curse_of_myrra pull request #508
Opened 2023-07-10 20:01 UTC by ncontinanza

The SocketConnectionManager is intended to be a Singleton object, but until now it was possible to have more than one instance when finishing a game and starting a new one. 

## Steps to test:
1. Launch a new game in your editor. Check that you have only one instance of the NetworkManager in the character selection scene, that is also alive in the BackendPlayground scene.
2. Pause the game and go back to the lobbies scene. Verify that the NetworkManager was destroyed in this step.
3. Launch a new game, and you should see only one instance of the NetworkManager in the character selection scene.

2023-07-10 20:14 UTC, tvillegas98 commented on client/ProjectSettings/ProjectSettings.asset
> +  AndroidKeystoreName: /Users/ncontinanza/key2.keystore
I think we should not push this change 🤔

2023-07-11 15:12 UTC, BertovDev requested changes

2023-07-11 15:12 UTC, BertovDev commented on client/Assets/Scripts/SocketConnectionManager.cs
> +            return;
This looks great. Just for curiosity why are you using `return` here?

2023-07-11 19:26 UTC, BertovDev requested changes

2023-07-11 19:26 UTC, BertovDev commented on client/Assets/Scenes/BackendPlayground.unity
Please remember that changes have to be done inside the respective prefab and then applied to the scene.
In this case this changed had to be done inside `CameraUI` prefab.

2023-07-11 19:38 UTC, ncontinanza commented on client/Assets/Scripts/SocketConnectionManager.cs
> +            return;
Because this case is the one in which the instance is a duplicate (that's why it's not null), so I call Destroy() to make sure that the Singleton has only one such component in the scene. And then return, because there's nothing else to do with that instance.

2023-07-11 19:42 UTC, ncontinanza commented on client/Assets/Scenes/BackendPlayground.unity
Right, it's fixed now.

2023-07-11 21:32 UTC, BertovDev approved these changes
Awesome , working fine!!

2023-07-12 15:22 UTC, BertovDev approved these changes

2023-07-12 15:37 UTC, manucamejo commented on server/lib/dark_worlds_server/engine/runner.ex
> +    current = gen_server_state.current_players - 1
Why we not removing the player from the list?

2023-07-12 16:24 UTC, martinacantaro commented
Followed the instructions:

- Created several Quick games
- Pausing games and going back to lobby worked fine every time.
- The Network Manager worked as expected.
- Creating lobbies and going back worked, but around 10% of the time I saw this bug where it kicks you back into the lobby and you have to click Back again. I made a video where it also shows when the Network Managers appears and disappears

https://github.com/lambdaclass/curse_of_myrra/assets/6120897/538babd9-3787-48f0-8971-379f43ce0b6a

2023-07-12 17:45 UTC, ncontinanza commented on server/lib/dark_worlds_server/engine/runner.ex
> +    current = gen_server_state.current_players - 1
Should be fixed now

2023-07-12 17:51 UTC, ncontinanza commented
> Followed the instructions:
> 
> * Created several Quick games
> * Pausing games and going back to lobby worked fine every time.
> * The Network Manager worked as expected.
> * Creating lobbies and going back worked, but around 10% of the time I saw this bug where it kicks you back into the lobby and you have to click Back again. I made a video where it also shows when the Network Managers appears and disappears
> 
>  bug.mov

That's an issue that we should take care of in another PR, it only happens in the editor. When you use your mouse to click on a button, a second click will be received if in the next scene there is another button under your mouse pointer. You can easily verify this if, after clicking a button, you quickly move the pointer to a side of the screen or somewhere else where you know there won't be a button in the next scene. On the contrary, if you click in a spot where there is a button in the next scene, you'll see the effect that you mentioned.

2023-07-12 21:25 UTC, BertovDev approved these changes
- [x] Tested in Unity Desktop
- [x] Tested in Android 11

2023-07-12 21:55 UTC, merged