Add new proto messages for player actions
lambdaclass/curse_of_myrra pull request #515
Opened 2023-07-11 17:20 UTC by tvillegas98

2023-07-24 23:35 UTC, manucamejo requested changes

2023-07-24 23:35 UTC, manucamejo commented on client/Assets/Scripts/PlayerMovement.cs
> +            walking = true;
Should we remove this?

2023-07-24 23:35 UTC, manucamejo commented on server/native/gamestate/src/game.rs
> +        player.action = PlayerAction::MOVING.clone();
Cloning is not necessary

2023-07-24 23:35 UTC, manucamejo commented on server/native/gamestate/src/player.rs
> +#[derive(rustler::NifTaggedEnum, Debug, Hash, Clone, PartialEq, Eq)]
If we remove the clone function, maybe we don't need these changes.

2023-07-24 23:35 UTC, manucamejo commented on client/Assets/Animations/Muflus/MuflusController.controller
> +    m_ConditionEvent: Skill1
Is this necessary?

2023-07-24 23:35 UTC, manucamejo commented on client/Assets/Scripts/EventsBuffer.cs
> +        GameEvent followingEventToRender = this.getNextEventToRender(pastTime + 30);
What happen if we don't have `following`?

2023-07-24 23:35 UTC, manucamejo commented on client/Assets/Scripts/Messages.pb.cs
> +    selectedCharacters_.Add(other.selectedCharacters_);
Why do we need this?

2023-07-24 23:35 UTC, manucamejo commented on client/Assets/Scripts/EventsBuffer.cs
> +    public bool playerIsMoving(ulong playerId, long pastTime)
Please, document a little this function.

2023-07-25 01:08 UTC, tvillegas98 commented on client/Assets/Scripts/Messages.pb.cs
> +    selectedCharacters_.Add(other.selectedCharacters_);
Protobuf generated this not me

2023-07-25 01:09 UTC, tvillegas98 commented on client/Assets/Scripts/EventsBuffer.cs
> +        GameEvent followingEventToRender = this.getNextEventToRender(pastTime + 30);
We will always have a following event, check the `getNextEventToRender`

2023-07-25 01:10 UTC, tvillegas98 commented on client/Assets/Animations/Muflus/MuflusController.controller
> +    m_ConditionEvent: Skill1
@saugon Did this, fixed a bug where muflus couldn't do a barrel roll while walking

2023-07-25 01:28 UTC, tvillegas98 commented on client/Assets/Scripts/PlayerMovement.cs
> +            walking = true;
Yes, now we can remove it

2023-07-25 02:33 UTC, tvillegas98 commented on server/native/gamestate/src/game.rs
> +        player.action = PlayerAction::MOVING.clone();
Done!

2023-07-25 02:34 UTC, tvillegas98 commented on server/native/gamestate/src/player.rs
> +#[derive(rustler::NifTaggedEnum, Debug, Hash, Clone, PartialEq, Eq)]
Done!

2023-07-25 02:43 UTC, tvillegas98 commented on client/Assets/Scripts/EventsBuffer.cs
> +    public bool playerIsMoving(ulong playerId, long pastTime)
D0one!

2023-07-25 14:40 UTC, manucamejo approved these changes

2023-07-25 16:48 UTC, ncontinanza requested changes
The movement is working fine, but the fixes from the commit `cc4f04200202cd9603f515fe36357ec5a35d09b4` seem to have lost their effect, and Muflus does not attack while walking, and H4ck does not stop moving to perform an attack.

2023-07-25 18:26 UTC, manucamejo approved these changes

2023-07-25 18:28 UTC, ncontinanza approved these changes

2023-07-25 18:28 UTC, merged