Pre Load GameScene
lambdaclass/curse_of_myrra pull request #550
Opened 2023-07-13 16:47 UTC by BertovDev

This PR pre load the game Scene in backendplayground.

This is the only way i found to do the mencioned. It you now another please comment it in this PR!

closes #538

2023-07-13 19:38 UTC, ncontinanza requested changes
Nice job! 
Tested locally in Unity editor and in an Android device, both worked fine.
Just left two little comments about the code

2023-07-13 19:38 UTC, ncontinanza commented on client/Assets/Scripts/LobbyManager.cs
> +        if (GameManager.Instance != null)
Maybe we could delegate this logic to a private method, so that BackToLobbyAndCloseConnection() doesn't have that much operational code.

2023-07-13 19:38 UTC, ncontinanza commented on client/Assets/Scripts/SocketConnectionManager.cs
> +                    // SceneManager.LoadScene("BackendPlayground");
Should this comment be removed?

2023-07-13 21:33 UTC, BertovDev commented on client/Assets/Scripts/LobbyManager.cs
> +        if (GameManager.Instance != null)
Seems correct. I will create another method. Thanks!!

2023-07-13 21:33 UTC, BertovDev commented on client/Assets/Scripts/SocketConnectionManager.cs
> +                    // SceneManager.LoadScene("BackendPlayground");
You right

2023-07-13 22:17 UTC, ncontinanza approved these changes
LGTM!

2023-07-18 20:46 UTC, tvillegas98 approved these changes
Nice improvement! 😄

2023-07-18 20:47 UTC, merged