Logs in game screen
lambdaclass/curse_of_myrra pull request #570
Opened 2023-07-18 17:21 UTC by BertovDev

This PR allows you to visualize console logs in screen , useful in mobile builds.
Also implements custom debug.log for only printing things when you desire ( touching a button in panel settings )

- `CustomDebugLog.CustomDebug(object message)` only works when activating `use Custom logs` in settings panel
- Show logs screen in `Show logs` button in settings panel

2023-07-19 15:42 UTC, tvillegas98 commented
Seems to be working well! Can we add the same button for every screen? it will be helpful

2023-07-20 16:20 UTC, BertovDev commented
> Seems to be working well! Can we add the same button for every screen? it will be helpful

Absolutely!!

2023-07-20 23:02 UTC, manucamejo commented
@BertovDev 

Why do the buttons appear in the lobbies scene?
<img width="668" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/20927859/23402e9c-e8bf-4cb3-bb88-8bb28c1e4c3b">

I can't scroll through the logs and Muflus is naked
<img width="623" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/20927859/60088e29-5bcf-4e38-9794-359827f2f485">

2023-07-31 15:51 UTC, ncontinanza requested changes

2023-07-31 15:51 UTC, ncontinanza commented on client/Assets/Scripts/CustomLogs.cs
> +        CustomDebugLog.CustomDebug("CUSTOMM!!");
I guess we should remove this line

2023-07-31 18:14 UTC, ncontinanza approved these changes

2023-08-01 15:47 UTC, tvillegas98 approved these changes
Nice work 😎

2023-08-01 15:47 UTC, merged