Improve metrics info display
lambdaclass/curse_of_myrra pull request #684
Opened 2023-07-28 21:24 UTC by ncontinanza

Closes #683 

This PR implements a refactor of the metrics that we show at the bottom of the screen. You can find a reference picture in the issue.

To test it, launch a new game and verify the changes in the new bar.

2023-07-31 16:48 UTC, BertovDev commented on client/Assets/Scenes/BackendPlayground.unity
If you only made changes in the CameraUi prefab remember to discard changes made in the scene.

If you made the changes in the prfab inside the scnee you have to go to the section override in the prefab inside the scene. Then Apply All and discard the Scene changes.

2023-07-31 16:49 UTC, BertovDev commented on client/Assets/Scripts/VersionsHashes.cs
> +        string hash = serverHash ? "Server# " + SocketConnectionManager.Instance.serverHash : "Client# "+ GitInfo.GetGitHash();
This should not be like this : `"Server #"`? same for the client

2023-07-31 16:50 UTC, BertovDev requested changes
Looks nice! I left you some comments. I will wait for your response so for now i will request changes 😔

2023-07-31 20:53 UTC, BertovDev submitted a review, later dismissed
Awesome!!!

2023-08-01 18:25 UTC, BertovDev approved these changes

2023-08-01 19:09 UTC, AngieDutra approved these changes
This looks great! ✨

2023-08-01 19:09 UTC, merged