Lobbies UI UX updates
lambdaclass/curse_of_myrra pull request #707
Opened 2023-08-02 16:56 UTC by AngieDutra

This PR:

- reverts lobbies list arregement
- makes the entire lobby container clickable
- Deletes scroll bar without deleting the scroll function
- Adds a "no lobbies yet" text

2023-08-02 17:24 UTC, tvillegas98 submitted a review, later dismissed
Nice improvements 😄 .

2023-08-02 17:27 UTC, tvillegas98 commented on client/Assets/Scripts/UIManager.cs
>          itemList.ForEach(el =>
I think before entering the foreach, you cando `itemList.Reverse();`

2023-08-02 17:27 UTC, tvillegas98 commented on client/Assets/Scripts/UIManager.cs
>          itemList.ForEach(el =>
And avoid having changing the list arrangement in each iteration

2023-08-02 17:33 UTC, AngieDutra commented on client/Assets/Scripts/UIManager.cs
>          itemList.ForEach(el =>
will do!

2023-08-02 17:53 UTC, BertovDev requested changes

2023-08-03 16:52 UTC, ncontinanza approved these changes
LGTM! 🚀

2023-08-03 17:16 UTC, BertovDev approved these changes
Looking and Working good! 🤩

2023-08-03 17:16 UTC, merged