Start documentation for entity interpolation
lambdaclass/curse_of_myrra pull request #755
Opened 2023-08-08 16:28 UTC by tvillegas98

This PR adds docs for Entity Interpolation in the Fluid Gameplay section

Closes #746

2023-08-09 14:28 UTC, manucamejo commented on docs/src/fluid_gameplay.md
> +As you can see, his movement feels weird sometimes it suddenly stops and that's not because Player 2 decided to stop, it is because we're updating their movement based what on the updates sent by the
"based what on the updates sent by the server." remove 'what'

2023-08-09 14:28 UTC, manucamejo commented on docs/src/fluid_gameplay.md
> +Theory behing Interpolation is that we render an X amount of time in the past what other player are doing, and that allows us to interpolate the movement. Let's suppose we're interpolating 100ms in t
"behing" -> behind

2023-08-09 14:28 UTC, manucamejo commented on docs/src/fluid_gameplay.md
> +Looks smoother now, doesn't it? Well, let's increase that interpolation time and turn on the server's ghost, this will allows us to see what exactly is Interpolation attacking
"allows" -> allow

2023-08-09 15:56 UTC, mgrunwaldt requested changes
Nice work, I left a small comment

2023-08-09 15:56 UTC, mgrunwaldt commented on docs/src/fluid_gameplay.md
> +As you can see, his movement feels weird sometimes it suddenly stops and that's not because Player 2 decided to stop, it is because we're updating their movement based what on the updates sent by the
I would put "our *player's* movement feels.."

2023-08-09 15:56 UTC, mgrunwaldt commented on docs/src/fluid_gameplay.md
> +Theory behing Interpolation is that we render an X amount of time in the past what other player are doing, and that allows us to interpolate the movement. Let's suppose we're interpolating 100ms in t
You are talking about "interpolate the movement", I don't know if people who never worked with this in the past will understand what this mean. Later on it's explained, but here you use the word before actually explaining what it means, I would try to go one step back and write it for someone who doesn't know anything about this subject before even using the word.

2023-08-09 20:17 UTC, tvillegas98 commented on docs/src/fluid_gameplay.md
> +Theory behing Interpolation is that we render an X amount of time in the past what other player are doing, and that allows us to interpolate the movement. Let's suppose we're interpolating 100ms in t
Yes. you're right, i'll be changing this to be more friendly to newcomers

2023-08-11 13:51 UTC, tvillegas98 commented on docs/src/fluid_gameplay.md
> +As you can see, his movement feels weird sometimes it suddenly stops and that's not because Player 2 decided to stop, it is because we're updating their movement based what on the updates sent by the
Done!

2023-08-11 13:51 UTC, tvillegas98 commented on docs/src/fluid_gameplay.md
> +Theory behing Interpolation is that we render an X amount of time in the past what other player are doing, and that allows us to interpolate the movement. Let's suppose we're interpolating 100ms in t
Done!

2023-08-11 13:51 UTC, tvillegas98 commented on docs/src/fluid_gameplay.md
> +Looks smoother now, doesn't it? Well, let's increase that interpolation time and turn on the server's ghost, this will allows us to see what exactly is Interpolation attacking
Done!

2023-08-16 14:47 UTC, mgrunwaldt approved these changes

2023-08-16 15:33 UTC, AngieDutra requested changes

2023-08-16 15:38 UTC, mgrunwaldt commented on docs/src/fluid_gameplay.md
> +As you can see, his movement feels that sometimes it suddenly stops and that's not because Player 2 decided to stop, it is because we're updating their movement based on the updates sent by the serve
Not sure I agree on this, if I read our player's movement I will automatically think on my player, not on player 2

2023-08-16 16:06 UTC, AngieDutra commented on docs/src/fluid_gameplay.md
> +As you can see, his movement feels that sometimes it suddenly stops and that's not because Player 2 decided to stop, it is because we're updating their movement based on the updates sent by the serve
player 2's could be an alternative but if not you could leave it as it is

2023-08-16 16:45 UTC, mgrunwaldt commented on docs/src/fluid_gameplay.md
> +As you can see, his movement feels that sometimes it suddenly stops and that's not because Player 2 decided to stop, it is because we're updating their movement based on the updates sent by the serve
lets go for player 2's

2023-08-16 17:04 UTC, AngieDutra submitted a review, later dismissed
LGTM! 💥

2023-08-23 16:24 UTC, ncontinanza requested changes

2023-08-23 16:24 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +Here we'll address the problems that arise from networking, how we solved some of them, and how we might improve these solutions in the future. I HIGHLY encourage anyone reading this to actually try
This part starts in the plural first-person, then changes to singular first-person and then goes back to the plural first-person. Maybe we could change the second sentence to "We HIGHLY encourage anyone..."

2023-08-23 16:24 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +For this topic, lets set up our scenario:
```suggestion
For this topic, let's set up our scenario:
```

2023-08-23 16:24 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +Our movement feels pretty smooth now, but what about Player 2?. His movement only updates every time we receive an update from the server and supposing we receive an update every 20ms, we are receivi
```suggestion
Our movement feels pretty smooth now, but what about Player 2?. His movement only updates every time we receive an update from the server and, supposing we receive an update every 20ms, we are receiving 50 game updates per second.
```

2023-08-23 16:24 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +The theory behind Interpolation is that we save the events returned by our server, allowing us to render movements that have already happened. In addition, we are able to predict the movement of the
```suggestion
The theory behind Interpolation is that we save the events returned by our server, allowing us to render movements that have already happened. In addition, we are able to predict the movement of the following events. Let's suppose we're interpolating 100ms in the past, a player's movement would look like this:
```

2023-08-23 16:24 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +Looks smoother now, doesn't it? Well, let's increase that interpolation time and turn on the server's ghost, this will allow us to see what exactly Interpolation is doing
```suggestion
Looks smoother now, doesn't it? Well, let's increase that interpolation time and turn on the server's ghost, this will allow us to see what exactly Interpolation is doing.
```

2023-08-23 16:24 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +1. We keep track of time that has passed since the first update
```suggestion
1. We keep track of the time that has passed since the first update.
```

2023-08-23 16:24 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +2. We store the last 20 updates sent by the server
```suggestion
2. We store the last 20 updates sent by the server.
```

2023-08-23 16:24 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +All of this code is in the `EventsBuffer.cs`. Where you can change the delta interpolation time as you please. Remember, the delta interpolation time is how much time in the past you will render, if
```suggestion
All of this code is in the `EventsBuffer.cs`, where you can change the delta interpolation time as you please. Remember, the delta interpolation time is how much time in the past you will render, if it's too high, you'll be lying too much to your players.
```

2023-08-23 16:24 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +As we said in the previous topic, we keep track of the accumulated time since we received the first update from the server to interpolate the movement. The theory behind this should work, but we foun
```suggestion
As we said in the previous topic, we keep track of the accumulated time since we received the first update from the server to interpolate the movement. The theory behind this should work, but we found that there were times where the interpolation ghosts differed too way much from the server. After a bit of research, we discovered that the problem had to do with using the [`Time.deltaTime`](https://docs.unity3d.com/ScriptReference/Time-deltaTime.html) that belongs to Unity. That amount of time is how much time has passed since the last frame to the current one. That sounds okay, but the problem is that the game editor/Android build/iOS build should be active in the screen, if you change tabs or let the game run in the background the `Time.DeltaTime` stops but the server doesn't and because of that all the operations get messed up. In order to solve this, we just changed it for Unix time in milliseconds.
```

2023-09-15 20:42 UTC, ncontinanza requested changes

2023-09-15 20:42 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +Typically, the more computing power you have, the higher your framerate. In Myrra, we show players their framerate in the bottom left corner of the screen. Its value is usually capped at `300`, and a
```suggestion
Typically, the more computing power you have, the higher your framerate. In Myrra, we show players their framerate in the bottom of the screen. Its value is usually capped at `300`, and anything below `30` will feel really bad to play. Most games run either at `30`, `60` or at an uncapped `FPS` rate.
```

2023-09-15 20:42 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +Typically, the more computing power you have, the higher your framerate. In Myrra, we show players their framerate in the bottom left corner of the screen. Its value is usually capped at `300`, and a
This was outdated, we changed that design a few weeks ago.

2023-09-15 20:42 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +- The second one is the result of network instability. Servers send game updates at a fixed frequency (the `tick rate`), but it would be wrong to assume clients get them at that same frequency. Somet
```suggestion
- The second one is the result of network instability. Servers send game updates at a fixed frequency (the `tick rate`), but it would be wrong to assume clients get them at that same frequency. Sometimes network packets/frames take longer than expected, sometimes they get lost and have to be retransmitted (we use `Websocket`, which uses `TCP` underneath). This means clients may not get any update from the server for a little while, only to then get a few of them all at once.
```

2023-09-15 20:42 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +Notice that, by doing this, we are "lying" to the player. When they move in a direction, they immediately see themselves forward, but that's not where they actually are; the server, which is the sour
```suggestion
Notice that, by doing this, we are "lying" to the player. When they move in a direction, they immediately see themselves forward, but that's not where they actually are; the server, which is the source of truth of the gamestate, still needs to process that command and send it out to every player. The higher the ping, the further the gamestate will differ from what the player sees on their screen. This is a tradeoff. The game feels better to play with prediction on, but lie to players too much and they might notice. They may see shots that look like they should miss hit them, because they are not seeing their character where it actually is.
```

2023-09-15 20:42 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +In other words, what we are doing is making evey character chase the server's latest position at their corresponding speed, showing movement gradually over the course of however many frames happen be
```suggestion
In other words, what we are doing is making every character chase the server's latest position at their corresponding speed, showing movement gradually over the course of however many frames happen between each tick. When we get a new updated position from the server, instead of immediately placing them there, we move characters smoothly from where they are up to where they need to be. This process of taking two discrete points and smoothing out the movement between them is sometimes called `interpolation`, `linear interpolation` or `lerp` for short.
```

2023-09-17 16:51 UTC, martinacantaro commented
Thanks for your detailed comments @ncontinanza ! They are all resolved now.

2023-09-18 13:28 UTC, ncontinanza approved these changes
LGTM! 🚀

2023-09-18 19:08 UTC, mgrunwaldt approved these changes

2023-09-18 19:08 UTC, merged