Animation Docs
lambdaclass/curse_of_myrra pull request #759
Opened 2023-08-08 18:43 UTC by BertovDev

2023-08-10 15:42 UTC, tvillegas98 commented on docs/src/animations.md
> +The animator is the interface to control the Mecanim animation system. We use it to add the animations and create a flow within them.
```suggestion
The animator is the interface to control the [Mecanim animation system](https://docs.unity3d.com/462/Documentation/Manual/MecanimAnimationSystem.html). We use it to add the animations and create a flow within them.
```

2023-08-10 15:44 UTC, tvillegas98 commented on docs/src/animations.md
> +Transitions have diffenrents settings to setup deppending of what you want, these are the most important.
```suggestion
Transitions have differents settings to setup deppending on what you want, these are the most important.
```

2023-08-10 16:00 UTC, tvillegas98 commented on docs/src/how_to_add_anim.md
> +When you have all your animations set , open the animatorController and drag the entry animation (Idle in our case) it will automatly connect to the entry state.
```suggestion
When you have all your animations set, open the animatorController and drag the entry animation (Idle in our case) it will automatically connect it to the entry state.
```

2023-08-10 16:00 UTC, tvillegas98 commented on docs/src/how_to_add_anim.md
> +Then drag and drop in the animator the rest of the animations.Now we are ready to create the transitions 🤙.
```suggestion
Then drag and drop into the animator the rest of the animations.Now we are ready to create the transitions 🤙.
```

2023-08-10 19:47 UTC, mgrunwaldt requested changes
Amazing work!! Left some minor grammar changes

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/animations.md
> +- Has Exit Time: Determinates a fixed time for a animation. Ignores any kind of transition parameter.
*an animation

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/animations.md
> +- `SkillBasic_start, Skill1c_start, Skill2c_start, Skill3c_start, Skill4c_start ( Booleans )` Not allways necessaries , we use them to concatenate animations.
*Not always necessary

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/animations.md
> +- `SkillBasic_start, Skill1c_start, Skill2c_start, Skill3c_start, Skill4c_start ( Booleans )` Not allways necessaries , we use them to concatenate animations.
Not sure if I follow what these booleans do by just reading this. (SkillBasic_start, Skill1c_start, Skill2c_start, Skill3c_start, Skill4c_start)

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/animations.md
> +- `Skillinfo.cs` an ScriptableObject with the skill information, here what we care about are the fields `hasModelAnimation`, `startAnimationDuration`, `executeAnimationDuration` and `animationSpeedMu
*a ScriplableObject. If the next word starts with the sound of a consonant then it should be a, if it starts with the sound of a vowel its an

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/animations.md
> +- `CustomLevelManager.cs` Where the buttons and mapped with the respective skill.
Maybe I would include the route to this scripts not just the name of the script

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/animations.md
> +- `SkillAnimationEvents.cs` is in change of changing the active skill playing and end the animation playing.
*it is in charge

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/animations.md
> +- `animationSpeedMultiplier`: (``float``) Determinate the play speed of the animation (used in the transition parameters if it is set).
*Determinates

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/animations.md
> +In this scripts is where all the skill-animation flows happen. It has all the scripts to start, execute, stop and change the animations. I believe this script leads to a separeted guide. Check the do
*script, happens

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/how_to_add_anim.md
> +To add the animations and adjust them to your character its simple:
*it's simple

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/how_to_add_anim.md
> +When you have all your animations set , open the animatorController and drag the entry animation (Idle in our case) it will automatically connect it to the entry state.
AnimatorController

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/how_to_add_anim.md
> +Then drag and drop into the animator the rest of the animations.Now we are ready to create the transitions 🤙.
animations. Now

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/how_to_add_anim.md
> +Select the transition, add the parameters conditions and Tweek the transition config with what you need ( Transition duration, Has Exit Time, etc), having in count what we learned in [Transitions](./
parameters', tweak

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/how_to_add_anim.md
> +Also have in mind to Tweek the values of `executeAnimationDuration`,`startAnimationDuration`,`animationSpeedMultiplier` in the respective scripteableObject of the skill.
tweak

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/skill.md
> +Lets start by explaining the differents methods we have in this script, since this script handle more things than just animations, lets focus only in the methods and flow of the animations.
*handles

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/skill.md
> +It is use to initialize the skills once the character is selected,  it maps the skill from the backend, the skill scripteableObject, the animationEvent.
*It is used. 
is it scripteableObject or ScriptableObject (no e after t)? Check it because I saw it written both ways throughout different texts

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/skill.md
> +This method clear each skill parameter, setting all booleans to false.
*clears

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/skill.md
> +This is in charge of begin the start animations (parameters with "_start" in their name, ex: "Skill1_start"), calls the methods mencioned before `ClearAnimator` and `ChangeCharacterState` and finally
This is in charge of beginning.
mentioned

2023-08-10 19:47 UTC, mgrunwaldt commented on docs/src/skill.md
> +#### This method is very importart due its the one which controls all the flow of the Skill animations.
because instead of due

2023-08-10 21:44 UTC, BertovDev commented on docs/src/animations.md
> +- `CustomLevelManager.cs` Where the buttons and mapped with the respective skill.
By route do you mean for example `Assets/Scripts/Skills/Skill.cs` ?

2023-08-10 21:46 UTC, BertovDev commented on docs/src/skill.md
> +It is use to initialize the skills once the character is selected,  it maps the skill from the backend, the skill scripteableObject, the animationEvent.
Yup it's ScriptableObject , I spelled wrong in this case

2023-08-14 20:37 UTC, mgrunwaldt requested changes
Just a few typos, the rest is perfect

2023-08-14 20:37 UTC, mgrunwaldt commented on docs/src/animations.md
> +- `SkillBasic_start, Skill1c_start, Skill2c_start, Skill3c_start, Skill4c_start ( Booleans )` Not always necessary , we use them to concatenate animations. For example if a skill have 2 different ani
For example, if a skill has two different animations that happen ...

2023-08-14 20:37 UTC, mgrunwaldt commented on docs/src/skill.md
> +It is used to initialize the skills once the character is selected,  it maps the skill from the backend, the skill ScripteableObject, the animationEvent.
ScriptableObject

2023-08-14 20:37 UTC, mgrunwaldt commented on docs/src/skill.md
> +This is in charge of beginning the start animations (parameters with "_start" in their name, ex: "Skill1_start"), calls the methods mentioned before `ClearAnimator` and `ChangeCharacterState` and fin
ScriptableObject

2023-08-14 20:50 UTC, BertovDev commented on docs/src/skill.md
> +This is in charge of beginning the start animations (parameters with "_start" in their name, ex: "Skill1_start"), calls the methods mentioned before `ClearAnimator` and `ChangeCharacterState` and fin
Awesome catches!

2023-08-14 20:52 UTC, mgrunwaldt approved these changes
Great work!!

2023-08-15 15:41 UTC, saugon submitted a review, later dismissed
Great job! 👌🏻

2023-08-15 18:44 UTC, mgrunwaldt requested changes

2023-08-15 18:44 UTC, mgrunwaldt commented on docs/src/animations.md
> +Tiempo maximo de duracion para hacer un eject para ambas
This is in spanish

2023-08-15 18:44 UTC, mgrunwaldt commented on docs/src/animations.md
> +- `startAnimationDuration`: (``float``) and `executeAnimationDuration`: (``float``) These methods represent the maxinum duration time to eject the skill animation
maximum

2023-08-15 19:05 UTC, AngieDutra requested changes

2023-08-15 19:05 UTC, AngieDutra commented on docs/src/how_to_add_anim.md
> +Also have in mind to Tweek the values of `executeAnimationDuration`,`startAnimationDuration`,`animationSpeedMultiplier` in the respective scripteableObject of the skill.
`Also have in mind` should be `Keep in mind` or `Bear in mind`

2023-08-15 19:05 UTC, AngieDutra commented on docs/src/how_to_add_anim.md
> +Also have in mind to Tweek the values of `executeAnimationDuration`,`startAnimationDuration`,`animationSpeedMultiplier` in the respective scripteableObject of the skill.
``executeAnimationDuration`,`startAnimationDuration`,`animationSpeedMultiplier`` is missing the spaces and a connector, it should be ``executeAnimationDuration`, `startAnimationDuration` and `animationSpeedMultiplier``

2023-08-15 22:22 UTC, AngieDutra approved these changes
A lot of great changes! 🤓

2023-08-16 14:30 UTC, marco-paulucci commented on docs/src/animations.md
> +Transitions have different settings to setup deppending on what you want, these are the most important.
```suggestion
Transitions have different settings to setup depending on what you want, these are the most important.
```

2023-08-16 14:32 UTC, marco-paulucci commented on docs/src/animations.md
> +- `SkillBasic, Skill1, Skill2, Skill3, Skill4 ( Booleans )` We use them to change the state of the animation and make the transition happen.
```suggestion
- `SkillBasic, Skill1, Skill2, Skill3, Skill4 (Booleans)` We use them to change the state of the animation and make the transition happen.
```

2023-08-16 14:49 UTC, marco-paulucci commented on docs/src/how_to_add_anim.md
> +To use the `animationSpeedMultiplier` set to use the Multiplier parameter checkbox in speed section of the animation.
```suggestion
To use the `animationSpeedMultiplier`, set to use the Multiplier parameter checkbox in the speed section of the animation.
```

2023-08-16 20:24 UTC, mgrunwaldt requested changes
There were some unaddressed comments by @AngieDutra , I just proposed the changes she asks

2023-08-16 20:24 UTC, mgrunwaldt commented on docs/src/animations.md
> +- `CustomLevelManager.cs` Where the buttons and mapped with the respective skill.
```suggestion
- `CustomLevelManager.cs` Where the buttons are mapped with the respective skill.
```

2023-08-16 20:24 UTC, mgrunwaldt commented on docs/src/skill.md
> +Lets start by explaining the differents methods we have in this script, since this script handles more things than just animations, lets focus only in the methods and flow of the animations.
```suggestion
Let's start by explaining the different methods we have in this script, since it handles more things than just animations, let's focus only in the methods and flow of the animations.
```

2023-08-16 20:24 UTC, mgrunwaldt commented on docs/src/skill.md
> +It is used to initialize the skills once the character is selected,  it maps the skill from the backend, the skill ScriptableObject, the animationEvent.
```suggestion
It is used to initialize the skills once the character is selected, it maps the skill from the backend, the skill ScriptableObject and the animationEvent.
```

2023-08-16 20:24 UTC, mgrunwaldt commented on docs/src/skill.md
> +#### This method is very importart because its the one which controls all the flow of the Skill animations.
```suggestion
#### This method is very important because it controls all the flow of the Skill animations.
```

2023-08-16 20:24 UTC, mgrunwaldt commented on docs/src/skill.md
> +This method implements the same logic as `StartFeedback` but for the parameters of all the skills without the "_start" in their name (ex: Skill1) and also use `executeAnimationDuration` instead of th
```suggestion
This method implements the same logic as `StartFeedback` but for the parameters of all the skills without the "_start" in their name (ex: Skill1). It also uses `executeAnimationDuration` instead of `startAnimationDuration` to end the animation.
```

2023-08-16 20:24 UTC, mgrunwaldt commented on docs/src/skill.md
> +Changes the movement machine state to Idle and set the animation parameter to false. This is used in the `SkillAnimationEvents` to end the animations.
```suggestion
Changes the movement machine state to Idle and sets the animation parameter to false. This is used in the `SkillAnimationEvents` to end the animations.
```

2023-08-16 20:24 UTC, mgrunwaldt commented on docs/src/skill.md
> +### This flowchart does only have in count the animation part of the method
```suggestion
### This flowchart only takes into account the animation part of the method
```

2023-08-16 20:32 UTC, mgrunwaldt approved these changes

2023-08-16 21:06 UTC, marco-paulucci approved these changes

2023-08-16 22:18 UTC, merged