Create feedback default container
lambdaclass/curse_of_myrra pull request #773
Opened 2023-08-10 16:45 UTC by BertovDev

2023-08-11 19:44 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +        ManageFeedbacks(player, playerUpdate);
Neat ⭐

2023-08-11 20:24 UTC, ncontinanza submitted a review, later dismissed
Nice job!

2023-08-15 14:52 UTC, AngieDutra submitted a review, later dismissed
Really like this refactor! 🎆

2023-08-15 18:04 UTC, mgrunwaldt requested changes
Great job, just a tiny suggestion

2023-08-15 18:35 UTC, mgrunwaldt submitted a review, later dismissed

2023-08-15 21:32 UTC, mgrunwaldt approved these changes

2023-08-15 21:57 UTC, AngieDutra approved these changes
LGTM ✨

2023-08-15 22:01 UTC, merged