Loot crate for health
lambdaclass/curse_of_myrra pull request #781
Opened 2023-08-11 19:06 UTC by AminArria

Closes #745 #450 #406 

- [x] Spawn loot for health crate in random position healing a random amount between 25 and 75
- [x] Player pickups loot while moving with joystick
- [x] Client shows/remove loot
- [x] GameSetting to tune loot spawn rate

Pending for front
- [ ] Proper model for the health loot. The `BattleManager` prefab has the script `Loot` which has a field to select the model for the health loot
- [ ] When picking up the health loot it gains health, but the effect shown is the same as when the player looses health (red flash)

2023-08-22 18:01 UTC, ncontinanza requested changes
Nice job! Just a few comments

2023-08-22 18:06 UTC, BertovDev commented on client/Assets/Scripts/Loot.cs
> +    private GameObject getLootObject(LootType lootType)
You are right!! thanks

2023-08-22 18:06 UTC, BertovDev commented on client/Assets/Scripts/SocketConnectionManager.cs
> +                    // updateLoots(game_event.Loots.ToList());
Yess

2023-08-22 19:24 UTC, mgrunwaldt requested changes
Good job. I left a few changes + a question. Besides that, its not looteable, its lootable, we should change it throughout the code,  (classes, uses in code, assets)

2023-08-22 19:24 UTC, mgrunwaldt commented on client/Assets/Scripts/OverlayEffect.cs
> +    public Shader Healshader;
```suggestion
    public Shader HealShader;
```

2023-08-22 19:24 UTC, mgrunwaldt commented on client/Assets/Scripts/PlayerFeedbacks.cs
>          if (auxHealth != playerHealth)
not sure I understand what auxHealth and playerHealth represent, can you explain in the comment?

2023-08-22 20:41 UTC, BertovDev commented on client/Assets/Scripts/PlayerFeedbacks.cs
>          if (auxHealth != playerHealth)
`auxHealth` is the client health and `playerHealth` is the server health. We are checking if their are different so we can display the damage feedback and then execute `healthComponent.SetHealth(playerUpdate.Health);` to match them.

2023-08-23 17:37 UTC, ncontinanza requested changes
Just a few more name changes and we're good to go.
Also look into renaming client/Assets/ScriptableObjects/Lootables/Looteable List.asset

2023-08-23 17:37 UTC, ncontinanza commented on client/Assets/Scripts/Lootable.cs
> +[CreateAssetMenu(fileName = "New Looteable", menuName = "CoM Looteable")]
```suggestion
[CreateAssetMenu(fileName = "New Lootable", menuName = "CoM Lootable")]
```

2023-08-23 17:37 UTC, ncontinanza commented on client/Assets/Scripts/LootableList.cs
> +[CreateAssetMenu(menuName = "CoM Looteable List", fileName = "Looteable List")]
```suggestion
[CreateAssetMenu(menuName = "CoM Lootable List", fileName = "Lootable List")]
```

2023-08-23 17:51 UTC, ncontinanza submitted a review, later dismissed
LGTM! 🚀

2023-08-25 21:55 UTC, saugon commented
Nice job! It's working as expected but there is something we need to change. @BertovDev

Loot.cs is currently managing the boxes, independent of the battle update logic (which is the one that handles updates between server and client). We should move the loot boxes management to Battle.cs, instead of having it in the Loot Update method.

Spoiler alert: there will be some improvements and changes after polishing some definitions around loot boxes 😁

2023-08-28 20:02 UTC, saugon submitted a review, later dismissed
Good work! 🚀

2023-08-28 20:13 UTC, ncontinanza submitted a review, later dismissed
Nice! 🚀

2023-08-28 21:04 UTC, ncontinanza approved these changes

2023-08-29 14:32 UTC, saugon approved these changes
Good work! 🚀

2023-08-29 14:48 UTC, ncontinanza approved these changes

2023-08-29 14:53 UTC, merged