How to create feedbacks docs
lambdaclass/curse_of_myrra pull request #784
Opened 2023-08-11 22:05 UTC by BertovDev

closes #780

2023-08-14 21:33 UTC, mgrunwaldt requested changes
good work, a few questions

2023-08-14 21:33 UTC, mgrunwaldt commented on docs/src/client_feedbacks.md
> +- `SetActiveFeedback(string name, bool activate)` Activate or deactivate the feedback that match with the name parameter depending on the boolean activate
*that matches the name parameter

2023-08-14 21:33 UTC, mgrunwaldt commented on docs/src/how_to_add_feedbacks.md
> +3. Now you have to increase the new state to the `StateEffects` and use the value of PlayerEffect. It's better with an example, if we would like to add the Effect state `Freeze`:
what do you mean by "Now you have to increase the new state to the `StateEffects` and use the value of PlayerEffect"?  Now you have to add ...?

2023-08-14 21:33 UTC, mgrunwaldt commented on docs/src/how_to_add_feedbacks.md
> +4. And now you are ready to go! Test it and enjoy the new feedback.🤩
Not sure I followed everything correctly. If the backend sends a feedback "Poisoned" for example, all you have to do is

1. Create the new prefab asset
2. Add this prefab to the feedback container
3. Add a new line in the StateEffects enum with the name of this prefab and the name of the feedback from the backend. The names should match between backend and frontend right?

And thats it?

2023-08-14 21:40 UTC, BertovDev commented on docs/src/how_to_add_feedbacks.md
> +3. Now you have to increase the new state to the `StateEffects` and use the value of PlayerEffect. It's better with an example, if we would like to add the Effect state `Freeze`:
My mistake!! I wanted to say :
3. Now you have to add the new state to the `StateEffects` enum and use the value of `PlayerEffect`.....

Thank u so much for notice it. I will change it.

2023-08-14 21:56 UTC, BertovDev commented on docs/src/how_to_add_feedbacks.md
> +4. And now you are ready to go! Test it and enjoy the new feedback.🤩
I believe my explication is not totally clear. So i would add some images to improve it. So for now let me answer you question, the steps to follow are:

1. Create the prefab asset with the particle system you desire
2. Inside the `FeedbackContainer` prefab you have to add the new prefab as a child and then add it to the list in the script component.
<img width="503" alt="Captura de pantalla 2023-08-14 a la(s) 18 45 00" src="https://github.com/lambdaclass/curse_of_myrra/assets/62818001/b8cf96f3-05e7-4089-a5d3-3a73540fd356">

3.  In  the `Battle.cs` script there is a Enum called `StateEffects` which only constains the states effects from the backend (Because we dont want the others effects such as rage, disarm, etc), you have to add the effect you want to display and match it with the `PlayerEffect ` enum that comes fron th backend.

``` 
    private enum StateEffects
    {
        Poisoned = PlayerEffect.Poisoned,
        Slowed = PlayerEffect.Slowed,
        Freeze = PlayerEffect.Freeze, <----- New effect added, with the same value as the backend version
    }
``` 
We do this to reduce the searches iterations in `ManageFeedbacks` method which is in charge of activate the feedbacks.

I can improve this explanation in the docs. So thank you for your feedback it made me realize how much can this be improved!

2023-08-15 18:34 UTC, mgrunwaldt commented on docs/src/client_feedbacks.md
> +- `SetActiveFeedback(string name, bool activate)` Activate or deactivate the feedback that that matches the name parameter depending on the boolean activate
the word that is repeated "that that matches"

2023-08-15 18:34 UTC, mgrunwaldt commented on docs/src/how_to_add_feedbacks.md
> +2. First, create the new Feedback prefab with the particle system you want, then add it to the `Client/Asssets/Feedbacks/States` folder.
aren't this two steps refering to the same?

2023-08-15 20:05 UTC, mgrunwaldt submitted a review, later dismissed
Great work!

2023-08-16 14:25 UTC, marco-paulucci reviewed
Great work!

2023-08-16 14:25 UTC, marco-paulucci commented on docs/src/client_feedbacks.md
> +#### Things to have in count before leraning how to implement new states feedback
`in mind`
`learning`
`states'`

2023-08-16 14:25 UTC, marco-paulucci commented on docs/src/client_feedbacks.md
> +Unity GameObject prefabs with a particle system component to show the particles effect of the state to display. You can find them in `Client/Asssets/Feedbacks/States`
Asssets -> Assets

2023-08-16 14:25 UTC, marco-paulucci commented on docs/src/client_feedbacks.md
> +You can find this prefab inside the `BattleManager` prefab, it serves as a connection between `Battle.cs` and `FeedbackContainer`. It implements a lot of methods for the Feedbacks, but the ones to ha
Feedbacks -> feedbacks

2023-08-16 14:25 UTC, marco-paulucci commented on docs/src/client_feedbacks.md
> +In this script is where we map the backend effects to the client effects. This script is huge! Fortunately, we only care about a couple of things here:
> In this script is where we map 

to

> In this script we map

2023-08-16 14:25 UTC, marco-paulucci commented on docs/src/client_feedbacks.md
> +In a nutshell, this method control all the flow of the feedback states.
```suggestion
In a nutshell, this method controls the complete flow of the feedback states.
```

2023-08-16 14:25 UTC, marco-paulucci commented on docs/src/how_to_add_feedbacks.md
> +1. First, create the new Feedback prefab with the particle system you want, then add it to the `Client/Asssets/Feedbacks/States` folder.
```suggestion
1. First, create the new Feedback prefab with the particle system you want, then add it to the `Client/Assets/Feedbacks/States` folder.
```

2023-08-16 14:25 UTC, marco-paulucci commented on docs/src/how_to_add_feedbacks.md
> +4. In the `Battle.cs` script there is a Enum called `StateEffects` which only constains the states effects from the backend (Because we dont want the others effects such as rage, disarm, etc), you ha
```suggestion
4. In the `Battle.cs` script there is an Enum called `StateEffects` which only contains the states effects from the backend (Because we don't want the others effects such as rage, disarm, etc), you have to add the effect you want to display and match it with the `PlayerEffect` enum that comes from the backend.
```

2023-08-16 14:25 UTC, marco-paulucci commented on docs/src/how_to_add_feedbacks.md
> + We store only these states to simplifly the search iterations in the `ManageFeedbacks` method.
```suggestion
 We store only these states to simplify the search iterations in the `ManageFeedbacks` method.
```

2023-08-16 14:47 UTC, BertovDev commented on docs/src/client_feedbacks.md
> +#### Things to have in count before leraning how to implement new states feedback
Thanks!! in the last one do you mean `state's`?

2023-08-16 14:52 UTC, BertovDev commented on docs/src/client_feedbacks.md
> +#### Things to have in count before leraning how to implement new states feedback
Aweomse!! Thank u so much!

2023-08-16 15:17 UTC, marco-paulucci approved these changes
LGTM!

2023-08-16 15:18 UTC, mgrunwaldt approved these changes
Great job!

2023-08-16 15:37 UTC, merged