Refactor projectile
lambdaclass/curse_of_myrra pull request #808
Opened 2023-08-22 13:45 UTC by AngieDutra

2023-08-23 19:33 UTC, BertovDev requested changes
The code in this PR is awesome! congrats. Just a few little comments.

- Warnings are being displayed in the console because of missing scripts in the characters prefabs. We should remove them.
- We should think a better way of instanciate objectPooler because we are instanciate gameObjects that we dont use never again, but this is out of the scope of this PR. Just a reminder.

2023-08-23 19:33 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +                .Select(p => p.GetProjectileFromSkill())
I believe this looks more clear.
```suggestion
                .Select(skill => skill.GetProjectileFromSkill())
```

2023-08-23 19:33 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +                .Where(p => p != null);
This is not bad, but it will be better like this:
```suggestion
                .Where(projectile => projectile != null);
```

Looks great anyways.

2023-08-23 19:33 UTC, BertovDev commented on client/Assets/Scripts/Skills/Skill.cs
> +        }
This can be simplified doing:
```suggestion
           return skillInfo.projectileInfo ? skillInfo.projectileInfo : null;

```

2023-08-23 19:33 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +            // for this, I need to keep on working in both this and ProjectileHandler scripts
Can we remove this now?

2023-08-23 19:53 UTC, AngieDutra commented on client/Assets/Scripts/Battle.cs
> +            // for this, I need to keep on working in both this and ProjectileHandler scripts
Yes! Will do

2023-08-23 20:15 UTC, BertovDev submitted a review, later dismissed
Looks great 😎🤙

2023-08-28 17:01 UTC, saugon commented on client/Assets/Scripts/Battle.cs
> +    void UpdateProjectileActions()
I think it would be better for code readability to extract each part of the logic (delete, update, explode) into different functions.

2023-08-28 17:28 UTC, AngieDutra commented on client/Assets/Scripts/Battle.cs
> +    void SetInitialProjectile()
I agree, will do!

2023-08-29 22:24 UTC, BertovDev requested changes

2023-08-30 16:28 UTC, AngieDutra commented on client/Assets/Scripts/Projectiles/SkillProjectile.cs
> +        projectileFeedback.transform.position = transform.position;
I did a refactor here so this was fixed by that too

2023-08-31 15:12 UTC, BertovDev requested changes
This is very well on the way. I leave some comments.

My review its not finished I will continue, but first i wanted t o leave this comments.

2023-08-31 15:12 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +    }
I believe it looks cleaner like this:
```
  void ClearProjectiles(Dictionary<int, GameObject> projectiles, List<Projectile> gameProjectiles)
    {
        foreach (int projKey in projectiles.Keys.ToList())
        {
            if (!gameProjectiles.Exists(x => (int)x.Id == projKey))
            {
                projectiles[projKey].GetComponent<SkillProjectile>().ClearProjectiles();
                projectiles.Remove(projKey);
            }
        }
    }
```

- You only need the keys so iterate over them instead of the whole dictionary
- You already know that the keys are `int` type varibles so the foreach looks more clear

2023-08-31 15:39 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +    }
```
    void ClearProjectiles(Dictionary<int, GameObject> projectiles, List<Projectile> gameProjectiles)
    {
        foreach (var projKey in projectiles.ToList())
        {
            if (!gameProjectiles.Exists(x => (int)x.Id == projKey.Key))
            {
                projKey.Value.GetComponent<SkillProjectile>().ClearProjectiles();
                projectiles.Remove(projKey.Key);
            }
        }
    }
```

This is another good approach

2023-08-31 15:47 UTC, BertovDev commented on client/Assets/Scripts/Utils/Utils.cs
>          GameObject objectPoolerGameObject = new GameObject();
```suggestion
        GameObject tempObjectPooler = new GameObject();
```

2023-08-31 20:45 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +    }
Cool, I like the first one better, as we only need the keys to do what we need there.

2023-08-31 21:06 UTC, AngieDutra commented on client/Assets/Scripts/Utils/Utils.cs
>          GameObject objectPoolerGameObject = new GameObject();
ObjectToPool is named correctly, `objectPooler.GameObjectToPool = objectToPool;`

2023-08-31 21:07 UTC, AngieDutra commented on client/Assets/Scripts/Battle.cs
> +    }
`projKey` is weird to read, I would go for `projectileKey` or `key`

2023-08-31 21:08 UTC, AngieDutra commented on client/Assets/Scripts/Projectiles/SkillProjectile.cs
> +    public void ProcessProjectilesCollision(GameObject projectileFeedback)
We did this already but it's good you think so too

2023-08-31 21:47 UTC, BertovDev commented on client/Assets/Scripts/Utils/Utils.cs
>          GameObject objectPoolerGameObject = new GameObject();
I believe I don't explain myself correctly. My correction was for the `objectPoolerGameObject` not the `objectToPool` so it will be like this:


` GameObject tempObjectPooler = new GameObject();`

2023-09-01 20:27 UTC, BertovDev submitted a review, later dismissed

2023-09-06 21:36 UTC, tvillegas98 submitted a review, later dismissed
Great work! I've read the description this time.

2023-09-07 14:15 UTC, mgrunwaldt submitted a review, later dismissed
Great Work

2023-09-07 14:53 UTC, saugon reviewed
Great work! I leave some last comments

2023-09-07 14:53 UTC, saugon commented on client/Assets/Scripts/Projectiles/ProjectileHandler.cs
> +    public void CreateProjectilePooler(HashSet<SkillInfo> skillInfoSet)
I'd change the function name to "CreateProjectilesPoolers"

2023-09-07 14:53 UTC, saugon commented on client/Assets/Scripts/Projectiles/ProjectileHandler.cs
> +        HashSet<SkillInfo> skillInfoSet,
I think it would be better to receive the projectile itself (and doing this, the projectileSkillName won't be necessary).

2023-09-07 14:53 UTC, saugon commented on client/Assets/Scripts/Projectiles/SkillProjectile.cs
> +    public void UpdateProjectilePosition(Vector3 position)
Since this class has been refactored and the functions are clearly instance methdos now, this function could be called _UpdatePosition_.

2023-09-07 14:53 UTC, saugon commented on client/Assets/Scripts/Projectiles/SkillProjectile.cs
> +    public void ProcessProjectileCollision()
Same as previous comment: _ProcessCollision_

2023-09-07 14:53 UTC, saugon commented on client/Assets/Scripts/Projectiles/SkillProjectile.cs
> +    public void ClearProjectile()
Same as previous comment: _Destroy_ or _Remove_

2023-09-07 16:32 UTC, saugon approved these changes
Awesomee! 🚀

2023-09-07 21:23 UTC, mgrunwaldt approved these changes

2023-09-07 21:26 UTC, merged