Feedback for basic skill
lambdaclass/curse_of_myrra pull request #813
Opened 2023-08-24 19:15 UTC by ncontinanza

Closes #810

2023-08-25 16:32 UTC, BertovDev commented on client/Assets/Scripts/Utils/Utils.cs
>  }
I know this is a first iteration but I believe this would be better to have it in `PlayerFeedbacks`.

What do you think?

2023-08-25 16:32 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +        Utils.ChangeCharacterMaterialColor(character, color);
Maybe better to have a method in `PlayerFeedbacks`?

What do you think?

2023-08-25 20:10 UTC, ncontinanza commented on client/Assets/Scripts/Utils/Utils.cs
>  }
I think it would lead to some coupling problems, as this is not only being used in the Battle class (where it would be easy to implement it using its instance of PlayerFeedbacks), but also in the CustomInputManager.

2023-08-25 20:10 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +        Utils.ChangeCharacterMaterialColor(character, color);
This one is definitely better.

2023-08-25 20:11 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +        Utils.ChangeCharacterMaterialColor(character, color);
Same as before

2023-08-30 21:24 UTC, mgrunwaldt requested changes

2023-08-30 21:24 UTC, mgrunwaldt commented on client/Assets/Scripts/AimDirection.cs
> +    public bool isInsideCone(GameObject player)
```suggestion
    public bool IsInsideCone(GameObject player)
```
functions in c# should start with capital letter, after the change is done please check where it's used

2023-08-31 17:11 UTC, BertovDev requested changes
Awesome!! some minor changes. Everythings else is amazing!

2023-08-31 17:11 UTC, BertovDev commented on client/Assets/Scripts/CustomInputManager.cs
> +        return PlayerIsInSkillProximityRange(p, skill);
Same here, to avoid multiple returns

```
  bool isMultiShot = skill.GetSkillName() == "MULTISHOT";

	return isMultiShot
            ? PlayerIsInSkillDirectionRange(p, skill)
            : PlayerIsInSkillProximityRange(p, skill);
```

2023-08-31 18:41 UTC, BertovDev submitted a review, later dismissed
Stunning! 🤙

2023-09-07 15:32 UTC, mgrunwaldt commented
Great work! We should also add feedback for H4CK Paralyze Ability
<img width="654" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/22064054/4d2c2489-3fca-411d-a6d2-66904cd70848">

2023-09-08 21:00 UTC, mgrunwaldt submitted a review, later dismissed

2023-09-08 21:28 UTC, AngieDutra requested changes

2023-09-08 21:28 UTC, AngieDutra commented on client/Assets/Scripts/CustomInputManager.cs
> +        CustomMMTouchJoystick joystick,
All joysticks are buttons, so I believe you could only use buttons and then use GetComponent<CustomMMTouchJoystick>() when needed

2023-09-08 21:28 UTC, AngieDutra commented on client/Assets/Scripts/CustomInputManager.cs
> +    private bool PlayerIsInSkillRange(GameObject p, Skill skill)
```suggestion
    private bool PlayerIsInSkillRange(GameObject player, Skill skill)

```

2023-09-08 21:28 UTC, AngieDutra commented on client/Assets/Scripts/CustomInputManager.cs
> +    private bool PlayerIsInSkillRange(GameObject p, Skill skill)
I would to this with all the following `p`

2023-09-11 15:15 UTC, AngieDutra requested changes

2023-09-11 15:15 UTC, AngieDutra commented on client/Assets/Scripts/CustomInputManager.cs
> +        //CustomMMTouchButton button = mobileButtons[trigger].GetComponent<CustomMMTouchButton>();
I think you forgot to delete this comment. Other than that, it looks great!

2023-09-12 15:26 UTC, BertovDev requested changes

2023-09-12 15:26 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +        Utils.ChangeCharacterMaterialColor(character, color);
This line is droping FPS by 15-30. This is happening becuase it is been called every frame for each player no matters if the color had changed or not. So its consuming a lot of resources. 
( Also its doing a For loop inside a Update and passing through each transform child , really expensive method )

A solution to this could be only calling this method for the players that have their material changed.

2023-09-12 19:23 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +        Utils.ChangeCharacterMaterialColor(character, color);
Nice catch! I made a similar optimization for the poisoned feedback as well.

2023-09-13 18:01 UTC, BertovDev reviewed
Nice! one last thing. I found that the method `ShowSkillRange` in `CustomInputManager` its also killing the performance a little bit. This can be easily fixed but I know that method was not implemented in the PR. 
So what do you think, fix it in this PR o make a new PR with the fix?
I can commit the fix in any of the options.

---DISMISSED---

2023-09-14 18:07 UTC, BertovDev approved these changes

2023-09-15 14:12 UTC, AngieDutra approved these changes
LGTM

2023-09-15 14:12 UTC, merged