Play sfx according to the player distance
lambdaclass/curse_of_myrra pull request #814
Opened 2023-08-24 19:18 UTC by BertovDev

This PR adds abilities sfx sounds by proximity

- New `3DSoundManager` prefab.You can find it in each character prefab. It contains a MMF_PLAYER component to control the SoundManager sounds of the abilities. Also contains a `Sound3DManager` with 2 methods:

`SetSfxSound(AudioClip sfx)` Sets the clip to play in the MMF_PLAYER
`PlaySfxSound()` Plays the MMF_PLAYER feedbacks.

and finally in SKill.cs instead of using` PlayAbilityStartSfx` from CharacterAbility we use `PlaySfxSound` the method named before from the `Sound3DManager`

closes #812

2023-08-30 20:59 UTC, ncontinanza submitted a review, later dismissed
Loud and clear 👌

2023-08-30 21:20 UTC, mgrunwaldt requested changes

2023-08-31 17:22 UTC, ncontinanza approved these changes

2023-08-31 19:44 UTC, mgrunwaldt approved these changes

2023-09-01 13:58 UTC, merged