Projectile documentation
lambdaclass/curse_of_myrra pull request #824
Opened 2023-08-25 19:29 UTC by AngieDutra

2023-08-25 20:40 UTC, ncontinanza requested changes
Just a few typos

2023-08-25 20:40 UTC, ncontinanza commented on docs/src/how_to_create_projectiles.md
> +Fist of all, you should create a projectile prefab. The vital thing is to add a `ProjectileHandler` component to it. For visual porpuses we recommend the prefab is composed of a projectile and its tr
```suggestion
First of all, you should create a projectile prefab. The vital thing is to add a `ProjectileHandler` component to it. For visual purposes, we recommend the prefab is composed of a projectile and its trail. Keep in mind that, if you choose to follow our recommendation, these GameObjects should be children of the prefab to which `ProjectileHandler` was applied to. Then, place the prefab in the `Resources` folder.
```

2023-08-25 20:40 UTC, ncontinanza commented on docs/src/how_to_create_projectiles.md
> +`game.rs` sets each projectile behaviour. In that file, you should setup the projectile's behaviour, its prefab name and to which skill it belons to.
```suggestion
`game.rs` sets each projectile behaviour. In that file, you should setup the projectile's behaviour, its prefab name and to which skill it belongs to.
```

2023-08-25 20:40 UTC, ncontinanza commented on docs/src/projectiles.md
> +On the other hand we created `ProjectileHandler.cs` to set all the projectile's actions. This script is attached to every projectile prefab. We are using **MMSimpleObjectPooler** to have a projectile
```suggestion
On the other hand we created `ProjectileHandler.cs` to set all the projectile's actions. This script is attached to every projectile prefab. We are using **MMSimpleObjectPooler** to have a projectiles pooler. Feel free to read the [documentation](https://corgi-engine-docs.moremountains.com/API/class_more_mountains_1_1_tools_1_1_m_m_simple_object_pooler.html) on this, but we will give you a quick overview in regards of why we use this. Object Pooling is a great way to optimize your projects and lower the burden that is placed on the CPU when having to rapidly create and destroy GameObjects. To set our pooler we created `SetProjectilePrefab()`. For this we need to send 3 values through parameter: a name for the GameObject that will be created with an **MMSimpleObjectPooler** component attached to it; the position where the **SimpleObjectPooler** list will be created; and the projectile prefab's name that will be used to fill the previously mentioned list, by default with a length of 10;
```

2023-08-25 20:40 UTC, ncontinanza commented on docs/src/projectiles.md
> +In `Battle.cs` we stablished three variables to handle the projectiles.
Actually☝️ those are two variables

2023-09-11 20:40 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +You can think of tick rate as the rate at which the client(CHECK: used to say "we") samples the gameplay. A higher tick rate means the client(CHECK) samples more frequently, and thus converge to a mo
What do you think of "You can think of tick rate as the rate at which the gameplay is sampled"?
Because the tick rate is currently being handled both in the server and in the client.

2023-09-11 20:40 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +You can think of tick rate as the rate at which the client(CHECK: used to say "we") samples the gameplay. A higher tick rate means the client(CHECK) samples more frequently, and thus converge to a mo
Further on, we could have "A higher tick rate means more frequent sampling, and thus converge..."

2023-09-11 20:40 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +//CHECK this might be one of the misunderstandings. slideshow is more comparable to FPS.
I'm not sure about this one, but we should solve it before merging.

2023-09-11 20:40 UTC, ncontinanza commented on docs/src/fluid_gameplay.md
> +The less hacky solution to this is to make move commands tell the server where you are now. Players know their own speed (CHECK: Who is the real agent in this sentence? Clients know their character s
I guess that whoever wrote this was thinking in the backend's representation of a player. Although the frame rate is only known by the client afaik.

2023-09-11 20:54 UTC, AngieDutra commented on docs/src/fluid_gameplay.md
> +The less hacky solution to this is to make move commands tell the server where you are now. Players know their own speed (CHECK: Who is the real agent in this sentence? Clients know their character s
Although It appears as changed in this PR I haven't changed it. Let me check what happened there

2023-09-11 21:01 UTC, AngieDutra commented on docs/src/fluid_gameplay.md
> +The less hacky solution to this is to make move commands tell the server where you are now. Players know their own speed (CHECK: Who is the real agent in this sentence? Clients know their character s
Looks like something didn't adjust when this branch previous base was merged to main. I fixed it.

2023-09-12 12:43 UTC, ncontinanza requested changes

2023-09-12 12:43 UTC, ncontinanza commented on docs/src/how_to_create_projectiles.md
> +On the other hand, `game.rs` sets each projectile behaviour. In that file, you should set the projectile's behaviour, to which skill it and to which skill it belongs to.
"you should set the projectile's behaviour, to which skill it and to which skill it belongs to." is there a word missing here?

2023-09-12 12:43 UTC, ncontinanza commented on docs/src/projectiles.md
> +In `UpdateProjectileActions()`, called in `Update()`, if a gameProjectile status is active, we compare the skill triggered with the skills in the HashSet. This is how we determine which skill is bein
I'm not sure about this one, maybe you meant something else.

2023-09-12 15:54 UTC, ncontinanza approved these changes

2023-09-13 20:04 UTC, mgrunwaldt approved these changes

2023-09-13 20:04 UTC, merged