Warning about mismatching client and server hashes
lambdaclass/curse_of_myrra pull request #825
Opened 2023-08-25 20:13 UTC by ncontinanza

Closes #674

2023-08-28 15:36 UTC, BertovDev requested changes

2023-08-28 15:36 UTC, BertovDev commented on client/Assets/Scripts/LobbyConnection.cs
> +        if (serverHash.Trim() != GitInfo.GetGitHash().Trim())
There is a problem here. When you change the server to Brasil or Europe the `serverHash` string is null.

2023-08-28 15:36 UTC, BertovDev commented on client/Assets/Scripts/LobbyConnection.cs
> +                    serverHash = response.server_version;
`response.server_version ` is returning null in Europe and Brasil servers

2023-08-28 15:49 UTC, BertovDev commented on client/Assets/Scripts/LobbyConnection.cs
> +                    serverHash = response.server_version;
Nevermind these servers do not have the changes deployed. I thinkg anything else its right

2023-08-28 16:11 UTC, BertovDev requested changes

2023-08-28 16:11 UTC, BertovDev commented on client/Assets/Scripts/LobbyConnection.cs
> +    public string versionHashesDescription = "Client and Server version hashes do not match.";
Do we really need these variables to be `public`? 
I believe they could all be `private`. 

Also in the future it will be better to have them in a different file, something like : ClientMessages or something like that

2023-08-28 21:20 UTC, ncontinanza commented on client/Assets/Scripts/LobbyConnection.cs
> +                    serverHash = response.server_version;
phew!

2023-08-28 21:22 UTC, ncontinanza commented on client/Assets/Scripts/LobbyConnection.cs
> +    public string versionHashesDescription = "Client and Server version hashes do not match.";
Actually they could be constants, I'll make this change.

2023-08-29 17:06 UTC, BertovDev approved these changes
Awesome!

2023-09-06 18:55 UTC, AminArria approved these changes

2023-09-06 18:58 UTC, merged