Poisoned healthbar feedback
lambdaclass/curse_of_myrra pull request #841
Opened 2023-09-01 15:41 UTC by ncontinanza

Closes #638 

This PR removes the current feedback for the Poisoned state. Instead of that, we'll now simply change the poisoned character's health bar color to green while the effect lasts.

As we currently don't have any ability that applies the Poisoned effect on an enemy, we'll have to test this new feature indirectly.

A simple way to test this is to simply negate the condition for this feedback. That is, go to Battle.cs and change 
```
if (playerUpdate.Effects.ContainsKey((ulong)PlayerEffect.Poisoned))
```
 for 
```
if (!playerUpdate.Effects.ContainsKey((ulong)PlayerEffect.Poisoned))
``` 
By doing this, when you start a new game, your character's health bar will be green during the whole match. 

A more realistic way to test it is to give this behaviour to another effect. For example, you can replace the Paralyzed case in Battle.cs for the following code:

```
        if (playerUpdate.Effects.ContainsKey((ulong)PlayerEffect.Paralyzed))
        {
            characterSpeed = 0f;
            healthBar.ForegroundColor = GetHealthBarGradient(MMColors.Green);
        }
        else
        {
            if (healthBar.ForegroundColor.Equals(GetHealthBarGradient(MMColors.Green)))
            {
                healthBar.ForegroundColor = GetHealthBarGradient(MMColors.BestRed);
            }
        }
```
This way, when you paralyze another character with H4ck, its health bar will turn green as if it were poisoned.

2023-09-05 16:07 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +        }
Right!

2023-09-05 16:09 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +    }
Absolutely

2023-09-07 14:49 UTC, mgrunwaldt approved these changes
Great work!

2023-09-07 22:07 UTC, AngieDutra requested changes
Check the overlay effects, damage feedback and death feedback of each character prefab. Also, make sure to checkout from main SkillRange and TerrainZone. Those should never be modified.

2023-09-07 22:23 UTC, AngieDutra approved these changes
Looking good! ✨

2023-09-08 21:09 UTC, mgrunwaldt approved these changes

2023-09-08 21:09 UTC, merged