Death and victory screen
lambdaclass/curse_of_myrra pull request #860
Opened 2023-09-04 17:20 UTC by ncontinanza

Closes #856 

When the last player dies, we stop handling the movement and stop the walking animation.

2023-09-11 22:26 UTC, mgrunwaldt submitted a review, later dismissed

2023-09-13 20:49 UTC, BertovDev requested changes
We could add in the Update inside `CustomLevelManager` one more validation to avoid unnecessary calls.

```
 if (GameHasEndedOrPlayerHasDied(gamePlayer) && !deathSplash.activeSelf)
        {
            StartCoroutine(ShowDeathSplash(player));
        }
```

`&& !deathSplash.activeSelf` added

2023-09-13 20:49 UTC, BertovDev commented on client/Assets/Scripts/Utils/Utils.cs
> +        return SocketConnectionManager.Instance.gamePlayers.Count == 0
Please correct me but I believe gamePlayers never reach 0 so this is useless.

2023-09-13 20:49 UTC, BertovDev commented on client/Assets/Scripts/UI/DeathSplash/DeathSplashManager.cs
> +    }
Create a const
private const int WINNER_POS = 1;


```
private int GetRanking()
    {
        bool isWinner = SocketConnectionManager.Instance.PlayerIsWinner(
            LobbyConnection.Instance.playerId
        );

        return isWinner ? WINNER_POS : Utils.GetAlivePlayers().Count() + 1;
    }
```

2023-09-15 19:09 UTC, mgrunwaldt approved these changes

2023-09-15 19:09 UTC, merged