Cel Shading + Lighting improvements
lambdaclass/curse_of_myrra pull request #882
Opened 2023-09-11 22:50 UTC by saugon

### What's new?
1. Added cel shading materials for each character.
2. Added post processing effects.
3. Tweaked lighting.

### References
#### Cel shading + lighting: before and after
![Screenshot 2023-09-11 at 19 44 13](https://github.com/lambdaclass/curse_of_myrra/assets/6811225/d8d8ce97-322c-4474-b876-b73f7cd37e21)
![Screenshot 2023-09-11 at 19 41 06](https://github.com/lambdaclass/curse_of_myrra/assets/6811225/040eda93-773c-4f28-8b59-5ef490bd0792)
#### Bloom effect
![Screenshot 2023-09-11 at 19 42 12](https://github.com/lambdaclass/curse_of_myrra/assets/6811225/ead865c0-4608-4c63-a82a-bbaac76df59e)

2023-09-12 13:23 UTC, ncontinanza commented
I noticed the following behaviour when playing with H4ck in my mobile phone and Muflus in my Unity editor. Am I missing some step before testing, or is there a bug?

https://github.com/lambdaclass/curse_of_myrra/assets/17294394/3523282d-c29e-464f-986c-c298dd065a0f


https://github.com/lambdaclass/curse_of_myrra/assets/17294394/23e5205c-bd36-4ae6-a4d2-c64a060d7694

2023-09-20 13:36 UTC, BertovDev requested changes
inside `CharacterBase` in the `PlayerName` prefab there is a `UmaMarks` gameObject with a missing script and a empty image component. I reload unity and remain still. It is expected to add a new functionality later?
<img width="197" alt="Captura de pantalla 2023-09-20 a la(s) 10 35 35" src="https://github.com/lambdaclass/curse_of_myrra/assets/62818001/6c62aa87-d0fc-4dcc-9f6a-cb9be07babe6">

2023-09-20 14:52 UTC, AngieDutra requested changes
https://github.com/lambdaclass/curse_of_myrra/assets/82987608/06e4c141-ce9f-4db5-8260-530d718ac66c

https://github.com/lambdaclass/curse_of_myrra/assets/82987608/faf3403b-37b8-47db-b9c0-51fce46ad7b1

- Players look too bright and in hack's case it dificults to see the damage feedback
- The red feedback in the screen when a player enters the kill zone starts a bit too late. Maybe we could make the first one appear a bit faster and if the damage is too great then the second one appears. I would check if it's possible to add some transition to it too.
- In main players used to turn red if they were within the attack range from another player. Now they don't give any feedback in that case.
- Defeated splash shows the player without any color (only white)

2023-09-25 19:18 UTC, mgrunwaldt approved these changes

2023-09-25 19:20 UTC, merged