Refresh refactor
lambdaclass/curse_of_myrra pull request #884
Opened 2023-09-12 19:33 UTC by AngieDutra

This PR solves issues #664 and #779 
It optimizes the way we refresh our lobbies list and changes the buttons styles (in lobbies scene) to fix ui and ux problems.

Issues to check if they were solved:
- Hold your finger in the Refresh button. It should no longer refresh constantly. Instead, it should refresh when you stop pressing on it.
- If you press the Refresh button it should no longer toggle as much between the empty list indicator and the lobbies. Instead it should show either one or the other until your next refresh. 
_Two things to take into account: now it may not show you a lobby if it took too long to fetch it. That is expected and it works like that in other games too. In that case you should refresh again; If you spam the Refresh button it may occur that a lobby list is shown after an empty list indicator. This is also expected behavior._
- If an error is shown after or while a button is pressed, your buttons should no longer stay in a pressed state.
_You can trigger an error to test this by shutting the server connection or pressing the server button and display the server options_

_Keep in mind the button changes were only made in the lobbies scene since a refactor of buttons styles is coming up_

2023-09-13 17:23 UTC, ncontinanza requested changes

2023-09-13 17:23 UTC, ncontinanza commented on client/Assets/Scripts/UIManager.cs
> +        lobbiesList = LobbyConnection.Instance.lobbiesList;
```suggestion
        lobbiesList = LobbyConnection.Instance.lobbiesList;
```

2023-09-13 17:23 UTC, ncontinanza commented on client/Assets/Scripts/UIManager.cs
> +        lobbiesList = LobbyConnection.Instance.lobbiesList;
Could we directly assign `LobbyConnection.Instance.lobbiesList` instead of creating a new List and overwriting it with the other one?

2023-09-13 19:09 UTC, BertovDev requested changes
Working good!
I believe you have 2 instances of `UIManager` in `LobbiesCameraUI.prefab` by mistake. Or it was intentionally?

- One instance in `OptionsContainer` and the other in `LobbiesContainer` prefabs

2023-09-14 21:23 UTC, AngieDutra commented
> Working good! I believe you have 2 instances of `UIManager` in `LobbiesCameraUI.prefab` by mistake. Or it was intentionally?
> 
> * One instance in `OptionsContainer` and the other in `LobbiesContainer` prefabs

It was a mistake! Good catch

2023-09-15 14:19 UTC, BertovDev approved these changes

2023-09-15 14:29 UTC, ncontinanza approved these changes

2023-09-15 14:30 UTC, merged