Map all characters sfx and separate sound channels
lambdaclass/curse_of_myrra pull request #901
Opened 2023-09-15 20:58 UTC by BertovDev

This PR adds all the sounds for the current characters we have and each ability.

Also refactor the mute/unmute and the slider system of the settings. Separating channels in Music/Sfx.

closes #895

2023-09-21 18:21 UTC, mgrunwaldt reviewed
I have a few questions / comments, not on the code but on the result:

1. Muflus barrell roll should start before (not sure if this is from implementation or if the actual sound track takes too long to start)
2. Muflus leap should coordinate better, the sound is slow and then has a stomp, the stomp should sound when muflus touches the ground. Question: Does every leap take exactly the same time, regardless of the length of the leap?
3. The radius for when to listen to an opponent should be much shorter, I am listening to sounds of characters I don't see on the screen, this can become really confusing
4.

2023-09-21 18:21 UTC, mgrunwaldt commented on client/Assets/Scripts/UI/ToggleAudio.cs
> +            && volumeSlider.value > 0.0001f
why not > 0?

2023-09-21 18:33 UTC, martinacantaro commented
Comments on how we could improve the sfx after we reviewed this with @BertovDev 
https://www.notion.so/lambdaclass/Music-feedback-17fb02c093d040bdbe9a5878e02d7a31

2023-10-12 15:23 UTC, ncontinanza requested changes

2023-10-12 15:23 UTC, ncontinanza commented on client/Assets/Scripts/UI/ToggleAudio.cs
> +            && volumeSlider.value > 0.0001f
@mgrunwaldt @BertovDev I recall this is a value defined in some TopDown Engine classes to represent the minimum volume that a track can reach (for some reason, it's never 0). However, it may lead to some confusion. I think it will be better if we define our own constant here, and use that value wherever we need to mute a track.

2023-10-18 20:35 UTC, ncontinanza approved these changes

2023-10-19 20:17 UTC, ncontinanza approved these changes

2023-10-20 14:44 UTC, agustinesco requested changes
When you enter to a game when you've muted the game through the icon in the menus the ingame volumes seems a bit weird

<img width="534" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/106101218/fa976fba-3d98-4b19-a355-e0d4c9e400d1">

the music slider is correctly muted but the sfx slider is at max and the icon seems muted

2023-10-20 17:47 UTC, BertovDev commented
> When you enter to a game when you've muted the game through the icon in the menus the ingame volumes seems a bit weird
> <img alt="Screenshot 2023-10-20 at 11 48 04" width="716" src="https://user-images.githubusercontent.com/106101218/276967024-2a292e29-7865-4e22-995d-0890ad2c5813.png"> <img alt="image" width="534" src="https://user-images.githubusercontent.com/106101218/276965619-fa976fba-3d98-4b19-a355-e0d4c9e400d1.png">
> 
> the music slider is correctly muted but the sfx slider is at max (you can hear the sfx) and the icon seems muted

Currently we only have the option to mute the music in the lobbies and we could implement a sfx mute button also. Nice catch this could be a new issue.

2023-10-20 17:53 UTC, agustinesco commented
> > When you enter to a game when you've muted the game through the icon in the menus the ingame volumes seems a bit weird
> > <img alt="Screenshot 2023-10-20 at 11 48 04" width="716" src="https://user-images.githubusercontent.com/106101218/276967024-2a292e29-7865-4e22-995d-0890ad2c5813.png"> <img alt="image" width="534" src="https://user-images.githubusercontent.com/106101218/276965619-fa976fba-3d98-4b19-a355-e0d4c9e400d1.png">
> > the music slider is correctly muted but the sfx slider is at max (you can hear the sfx) and the icon seems muted
> 
> Currently we only have the option to mute the music in the lobbies and we could implement a sfx mute button also. Nice catch this could be a new issue.

Oh okey , it was a misunderstanding. I though this button would mute every sound not only the music, thanks for explaining!

2023-10-20 18:12 UTC, agustinesco commented on client/Assets/Scripts/UI/ToggleAudio.cs
>      }
I think we should update the volume sprite here too, because if we are muted and then increase only the volume the sprite doesn't change from the muted one

2023-10-20 18:56 UTC, BertovDev commented on client/Assets/Scripts/UI/ToggleAudio.cs
>      }
Awesome, another good catch.

2023-10-20 20:25 UTC, agustinesco approved these changes
LGTM!

2023-10-20 20:25 UTC, agustinesco commented on client/Assets/Scripts/UI/ToggleAudio.cs
>      }
Nice!

2023-10-23 15:31 UTC, ncontinanza approved these changes

2023-10-23 15:31 UTC, merged