Setup player abilities dynamically
lambdaclass/curse_of_myrra pull request #907
Opened 2023-09-18 21:30 UTC by BertovDev

2023-09-19 18:25 UTC, AngieDutra requested changes
Also, I see this error and I would like to know if you see it too

https://github.com/lambdaclass/curse_of_myrra/assets/82987608/aae1ed9a-3b90-4a81-8bed-2c7877ab31de

2023-09-19 18:25 UTC, AngieDutra commented on client/Assets/Scripts/CoMCharacter.cs
> +    public List<SkillInfo> skills;
You already had a list of this in line 24 of this file

2023-09-20 14:43 UTC, AngieDutra approved these changes
Great job!

2023-09-26 12:42 UTC, ncontinanza submitted a review, later dismissed
Awesome!

2023-09-26 19:37 UTC, mgrunwaldt commented
While testing this branch (after merging main to it) I don't see h4ck's projectiles:

https://github.com/lambdaclass/curse_of_myrra/assets/22064054/154ee10c-14ad-42b4-bc44-758405de34a6

This is the error it logs:
<img width="1095" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/22064054/71caadee-0f00-4703-8453-315b6c2f49f6">
<img width="1047" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/22064054/0f6a3e57-7cfa-4af7-93ff-0bfc5c269cff">

2023-10-10 13:32 UTC, ncontinanza approved these changes

2023-10-18 20:40 UTC, ncontinanza approved these changes

2023-10-19 19:23 UTC, AngieDutra approved these changes
Great work! LGTM ✨

2023-10-19 19:35 UTC, merged