Uma elnars mark
lambdaclass/curse_of_myrra pull request #908
Opened 2023-09-18 23:53 UTC by martinacantaro

Closes https://github.com/lambdaclass/curse_of_myrra/issues/802

2023-09-20 15:15 UTC, ncontinanza commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +// TODO: this could probably be a part of another class
I'll look after this when #882 is merged.

2023-09-20 18:06 UTC, BertovDev requested changes

2023-09-20 18:06 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +            player
Same here

2023-09-20 18:06 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +                player
You already have a reference to the character, it is been pass by parameter in the method. So you can do

```
character.characterBase.GetComponent<CharacterFeedbackManager()
.RemoveMarks(playerUpdate.Id);
```

2023-09-20 18:09 UTC, BertovDev requested changes

2023-09-20 18:09 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +                    .DisplayUmaMarks(playerUpdate.Id);
You already have a reference to the character, it is been pass by parameter in the method. So you can do

```
character.characterBase.GetComponent<CharacterFeedbackManager()
.DisplayUmaMarks(playerUpdate.Id);;
```

2023-09-20 18:09 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +                .RemoveMarks(playerUpdate.Id);
Same here:
```
       character.characterBase.GetComponent<CharacterFeedbackManager()
.RemoveMarks(playerUpdate.Id);
```

2023-09-20 18:51 UTC, AminArria requested changes
Changes to NIF need to go to [lambda_game_engine](https://github.com/lambdaclass/lambda_game_engine)

2023-09-20 18:51 UTC, AminArria commented on server/native/gamestate/src/game.rs
This changes would need to go in [lambda_game_engine](https://github.com/lambdaclass/lambda_game_engine)

2023-09-20 19:21 UTC, ncontinanza commented on server/native/gamestate/src/game.rs
Done! https://github.com/lambdaclass/lambda_game_engine/pull/3

2023-09-20 20:22 UTC, ncontinanza commented on client/Assets/Scripts/UmaMarks.cs
> +            GetComponent<Image>().sprite = mark1;
I didn't know it was possible to do this with fields of the same object! 
Cool optimization 👍

2023-09-20 21:39 UTC, ncontinanza commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +    public GameObject umaMarks;
I guess we could have a reference to the UmaMark script in the CharacterFeedbackManager to avoid this

2023-09-20 21:41 UTC, ncontinanza commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +        umaMarks.SetActive(true);
This won't be necessary if we implement it as I commented above

2023-09-20 21:41 UTC, ncontinanza commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +            umaMarks.SetActive(false);
This won't be necessary if we implement it as I commented above

2023-09-20 21:43 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +                    .DisplayUmaMarks(playerUpdate.Id);
Right!

2023-09-21 20:09 UTC, martinacantaro commented
> Changes to NIF need to go to [lambda_game_engine](https://github.com/lambdaclass/lambda_game_engine)

Done in this PR! https://github.com/lambdaclass/lambda_game_engine/pull/3

2023-09-21 20:12 UTC, AminArria submitted a review, later dismissed
LGTM, remember to first merge the PR in the engine

2023-09-21 20:55 UTC, BertovDev commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +    public UmaMarks umaMarksScript;
You have 2 references to the same GameObject , by referencing only the Script you have acces to the `.gameObject` beucase the script is a component of it.

Also in the `CharacterBase` prefab UmaMarks script reference is missing.

2023-09-21 21:13 UTC, BertovDev submitted a review, later dismissed
Awesome!!

2023-09-22 13:37 UTC, BertovDev submitted a review, later dismissed

2023-09-22 18:16 UTC, mgrunwaldt commented on client/Assets/Scripts/Battle.cs
> +                    .DisplayUmaMarks(playerUpdate.Id);
This will probably need a refactor when we want to add more marks

2023-09-22 18:16 UTC, mgrunwaldt commented on client/Assets/Scripts/Battle.cs
> +                .RemoveMarks(playerUpdate.Id);
Same here, now that we want more marks this will remove all marks if you don't have elnar's right?

2023-09-22 18:16 UTC, mgrunwaldt commented on client/Assets/Scripts/Battle.cs
> +    private ulong GetEffectCausedBy(Player playerUpdate, PlayerEffect effect)
I would rename this method, if I read getEffectCaused by I would expect the behaviour to be that it returns the effect caused by a player, not the player that causes the effect.

2023-09-22 18:16 UTC, mgrunwaldt commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +    public void DisplayUmaMarks(ulong markId)
In battle.cs line 926 you call this method by sending playerUpdate.Id as parameter, and now the name of the variable you receive here is markId. What are you actually using, the id of the current mark or of the player update?

2023-09-22 18:16 UTC, mgrunwaldt commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +    public void RemoveMarks(ulong markId)
same comment as above

2023-09-25 20:08 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +                .RemoveMarks(playerUpdate.Id);
Yes, I kept the code from #685 to have a first working version, but I'll improve it in #912

2023-09-25 20:09 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +    private ulong GetEffectCausedBy(Player playerUpdate, PlayerEffect effect)
Will do. GetEffectCauser() sounds better?

2023-09-25 20:13 UTC, ncontinanza commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +    public void DisplayUmaMarks(ulong markId)
Currently it's a player id, I'll do the change

2023-09-25 20:14 UTC, mgrunwaldt commented on client/Assets/Scripts/Battle.cs
> +    private ulong GetEffectCausedBy(Player playerUpdate, PlayerEffect effect)
yes sounds perfect!

2023-09-25 20:16 UTC, ncontinanza commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +    public void DisplayUmaMarks(ulong markId)
I'm temporarily using the player's id to identify the mark. It's one of the things that I'm willing to change soon, when we can have multiple marks per player.

2023-09-25 20:23 UTC, mgrunwaldt approved these changes

2023-09-25 21:49 UTC, BertovDev approved these changes

2023-09-26 11:46 UTC, merged