Uma Yugen's Mark
lambdaclass/curse_of_myrra pull request #912
Opened 2023-09-20 17:06 UTC by ncontinanza

Closes #803

2023-09-20 18:53 UTC, AminArria requested changes
Changes to the NIFs need to go to [lambda_game_engine](https://github.com/lambdaclass/lambda_game_engine)

2023-09-20 18:53 UTC, AminArria commented on server/native/gamestate/src/player.rs
This changes need to go to [lambda_game_engine](https://github.com/lambdaclass/lambda_game_engine)

2023-09-21 19:30 UTC, ncontinanza commented on server/native/gamestate/src/player.rs
Done!

2023-09-28 21:32 UTC, mgrunwaldt commented on client/Assets/Scripts/Battle.cs
> +    private bool healthBarIsGreen;
I think we dont use this anymore

2023-09-28 21:32 UTC, mgrunwaldt commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +    public void DisplayEffectMarks(ulong playerId, PlayerEffect effect)
Now that we are sending the mark we want to display, I would rename to DisplayEffectMark

2023-09-28 21:32 UTC, mgrunwaldt commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +    public void RemoveMarks(ulong playerId, PlayerEffect effect)
same comment as above

2023-09-28 21:42 UTC, mgrunwaldt approved these changes

2023-10-02 20:37 UTC, martinacantaro approved these changes
Playtested and approved!

2023-10-02 20:39 UTC, merged