Cyan health bar for current player
lambdaclass/curse_of_myrra pull request #949
Opened 2023-10-06 15:39 UTC by ncontinanza

2023-10-18 16:53 UTC, BertovDev requested changes
Healthbar looks and works awesome and the only problem we have its that the character prefabs have missing assings in characterFeedbacks Script. 
Merging main, overriding the prefab and assigning the m again should be fine.

<img width="310" alt="Captura de pantalla 2023-10-18 a la(s) 13 52 31" src="https://github.com/lambdaclass/curse_of_myrra/assets/62818001/30630f70-18a0-4324-a54c-50283a010ce2">

2023-10-19 15:26 UTC, BertovDev submitted a review, later dismissed

2023-10-19 21:28 UTC, BertovDev requested changes

2023-10-19 21:28 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +        ].ForegroundBar.GetComponent<Image>();
This is throwing me an error when killing a BOT. I didint try with a real player but i supposed the same will happend.

Error:
<img width="1284" alt="Captura de pantalla 2023-10-19 a la(s) 18 19 29" src="https://github.com/lambdaclass/curse_of_myrra/assets/62818001/e91b31b3-0261-404f-88b3-81752db10f98">


Can be fixed with:

```
        var healthBarFront = player
            .GetComponentInChildren<MMProgressBar>()
            .ForegroundBar.GetComponent<Image>();
```

2023-10-20 17:51 UTC, BertovDev submitted a review, later dismissed

2023-10-20 20:38 UTC, BertovDev approved these changes

2023-10-20 20:51 UTC, AngieDutra approved these changes
Great final changes!

2023-10-20 21:00 UTC, BertovDev approved these changes

2023-10-20 21:01 UTC, merged