Crate and Spawn sfx
lambdaclass/curse_of_myrra pull request #951
Opened 2023-10-06 19:19 UTC by BertovDev

This PR adds sfx for the crates and spawn

2023-10-11 14:58 UTC, ncontinanza approved these changes

2023-10-19 21:13 UTC, agustinesco requested changes

2023-10-19 21:13 UTC, agustinesco commented on client/Assets/Scripts/Loot.cs
> +        return false;
Can we do something like this here?

```
return loots.Any(l => l.id == id)
```

2023-10-19 21:13 UTC, agustinesco commented on client/Assets/Scripts/Loot.cs
> +        string type = GetLootType(id);
Since we already have the lootObject can't we do `lootObject.type` here? if so maybe we could remove `GetLootType` method too

2023-10-19 21:36 UTC, BertovDev commented on client/Assets/Scripts/Loot.cs
> +        return false;
Yess, this is a much cleaner solution. Great one!!

2023-10-19 21:38 UTC, BertovDev commented on client/Assets/Scripts/Loot.cs
> +        string type = GetLootType(id);
No we cant, becuase lootObject is a GameObject and it dont have the field type. But instead we can do a method called `GetLoot` that returns a `LootItem` which contains both lootObject and type. 

Nice catch!!

2023-10-19 21:53 UTC, agustinesco commented on client/Assets/Scripts/Loot.cs
> +        return false;
Nice!

2023-10-19 21:53 UTC, agustinesco commented on client/Assets/Scripts/Loot.cs
> +        string type = GetLootType(id);
Sounds good

2023-10-19 21:56 UTC, agustinesco approved these changes
LGTM! sounds are working as expected

2023-10-19 22:11 UTC, ncontinanza approved these changes

2023-10-19 22:11 UTC, merged