Manage Feedback Refactor
lambdaclass/curse_of_myrra pull request #971
Opened 2023-10-10 21:20 UTC by BertovDev

This PRs abstract functionalities referred to the Feedbacks of the `Battle.cs` .

- Remove repetitive code for the Uma marks and moved to the `CharacterFeedbackManager` script

2023-10-11 15:00 UTC, ncontinanza commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +    public void HandleUmMarks(Player playerUpdate)
Watch out for the typo (`HandleUmaMarks`)

2023-10-11 15:18 UTC, ncontinanza submitted a review, later dismissed
Much cleaner now!

2023-10-19 19:44 UTC, BertovDev commented on messages.proto
> +    NONE = 18;
I could run the make gen-protobuf in the server side. For now just using it as a placeholder. But it will be good to have a NONE state in the back

2023-10-19 19:50 UTC, AngieDutra approved these changes
Nice! ✨ I also tested on Android

2023-10-19 20:31 UTC, ncontinanza requested changes

2023-10-19 20:31 UTC, ncontinanza commented on client/Assets/Scripts/Battle.cs
> +        feedbackManager.HandleUmMarks(playerUpdate);
You fixed the typo but didn't change it here 😅

2023-10-19 20:36 UTC, BertovDev commented on client/Assets/Scripts/Battle.cs
> +        feedbackManager.HandleUmMarks(playerUpdate);
Thaks you🤦‍♂️

2023-10-19 20:44 UTC, AngieDutra approved these changes
still LGTM!

2023-10-19 21:11 UTC, ncontinanza approved these changes

2023-10-19 21:11 UTC, merged