Camera init cinematic
lambdaclass/curse_of_myrra pull request #979
Opened 2023-10-18 15:00 UTC by BertovDev

This PR add a cinematic introduction to the battle Scene, includes:

- A loading screen that helps to hide the Init phase of the Map, players and camera
- A cinematic that shows part of the map and finish on your character
- A UI splash with an animation and text.

Relatated issues:

#989 
#988 

closes #969 

<img width="497" alt="Captura de pantalla 2023-10-18 a la(s) 11 59 52" src="https://github.com/lambdaclass/curse_of_myrra/assets/62818001/696d5e0e-6b2c-4d10-b49b-42f94b4c800c">

- [x] Tested in Unity Desktop
- [x] Tested in Android

2023-10-19 22:13 UTC, agustinesco requested changes
Testing the pr i found out that in some screens the message doesn't fully cover the screen in particular with the "motorola moto E" simulator:
<img width="830" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/106101218/fc7987af-17ea-4cec-95b2-3f5e5ff7f49a">

Also when we reconnect to a game we got the same message with the same camera movement. Maybe we could change the message or omit the camera movement on the reconnect escenarios, what do you think?

2023-10-20 19:52 UTC, ncontinanza requested changes

2023-10-20 19:52 UTC, ncontinanza commented on client/Assets/Scripts/CustomLevelManager.cs
> +    GameObject loadinScreen;
```suggestion
    GameObject loadingScreen;
```

2023-10-20 19:52 UTC, ncontinanza commented on client/Assets/Scripts/CustomLevelManager.cs
> +            loadinScreen.SetActive(false);
```suggestion
            loadingScreen.SetActive(false);
```

2023-10-20 19:52 UTC, ncontinanza commented on client/Assets/Scripts/CustomLevelManager.cs
> +            loadinScreen.SetActive(false);
```suggestion
            loadingScreen.SetActive(false);
```

2023-10-20 19:52 UTC, ncontinanza commented on client/Assets/Scripts/CustomLevelManager.cs
> +    int roundupbyten(int i)
```suggestion
    int roundUpByTen(int i)
```

2023-10-20 19:52 UTC, ncontinanza commented on client/Assets/Scenes/Battle.unity
> +      propertyPath: loadinScreen
This should be changed to fix the typo as well

2023-10-23 19:04 UTC, agustinesco approved these changes
LGTM!

2023-10-23 21:27 UTC, agustinesco submitted a review, later dismissed

2023-10-25 19:22 UTC, ncontinanza submitted a review, later dismissed
LGTM!

2023-10-26 16:18 UTC, agustinesco approved these changes
LGTM!

2023-10-26 16:23 UTC, ncontinanza approved these changes

2023-10-26 16:23 UTC, merged